"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class AccessToken(object):
    """Implementation of the 'AccessToken' model.

    Attributes:
        sid (str): A 34 character string that uniquely identifies this Access Token.
        account_sid (str): The unique SID identifier of the Account.
        service_sid (str): The unique SID identifier of the Verify Service.
        entity_identity (str): The unique external identifier for the Entity of the
            Service.
        factor_type (AccessTokenEnumFactorTypes): The Type of the Factor. Currently
            only `push` is supported.
        factor_friendly_name (str): A human readable description of this factor, up
            to 64 characters. For a push factor, this can be the device's name.
        token (str): The access token generated for enrollment, this is an encrypted
            json web token.
        url (str): The URL of this resource.
        ttl (int): How long, in seconds, the access token is valid. Max: 5 minutes
        date_created (datetime): The date that this access token was created, given
            in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sid": "sid",
        "account_sid": "account_sid",
        "service_sid": "service_sid",
        "entity_identity": "entity_identity",
        "factor_type": "factor_type",
        "factor_friendly_name": "factor_friendly_name",
        "token": "token",
        "url": "url",
        "ttl": "ttl",
        "date_created": "date_created",
    }

    _optionals = [
        "sid",
        "account_sid",
        "service_sid",
        "entity_identity",
        "factor_type",
        "factor_friendly_name",
        "token",
        "url",
        "ttl",
        "date_created",
    ]

    _nullables = [
        "sid",
        "account_sid",
        "service_sid",
        "entity_identity",
        "factor_friendly_name",
        "token",
        "url",
        "date_created",
    ]

    def __init__(
        self,
        sid=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        service_sid=APIHelper.SKIP,
        entity_identity=APIHelper.SKIP,
        factor_type=APIHelper.SKIP,
        factor_friendly_name=APIHelper.SKIP,
        token=APIHelper.SKIP,
        url=APIHelper.SKIP,
        ttl=0,
        date_created=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccessToken instance."""
        # Initialize members of the class
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if service_sid is not APIHelper.SKIP:
            self.service_sid = service_sid
        if entity_identity is not APIHelper.SKIP:
            self.entity_identity = entity_identity
        if factor_type is not APIHelper.SKIP:
            self.factor_type = factor_type
        if factor_friendly_name is not APIHelper.SKIP:
            self.factor_friendly_name = factor_friendly_name
        if token is not APIHelper.SKIP:
            self.token = token
        if url is not APIHelper.SKIP:
            self.url = url
        self.ttl = ttl
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        service_sid =\
            dictionary.get("service_sid")\
            if "service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        entity_identity =\
            dictionary.get("entity_identity")\
            if "entity_identity" in dictionary.keys()\
                else APIHelper.SKIP
        factor_type =\
            dictionary.get("factor_type")\
            if dictionary.get("factor_type")\
                else APIHelper.SKIP
        factor_friendly_name =\
            dictionary.get("factor_friendly_name")\
            if "factor_friendly_name" in dictionary.keys()\
                else APIHelper.SKIP
        token =\
            dictionary.get("token")\
            if "token" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        ttl =\
            dictionary.get("ttl")\
            if dictionary.get("ttl")\
                else 0
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sid,
                   account_sid,
                   service_sid,
                   entity_identity,
                   factor_type,
                   factor_friendly_name,
                   token,
                   url,
                   ttl,
                   date_created,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _entity_identity=(
            self.entity_identity
            if hasattr(self, "entity_identity")
            else None
        )
        _factor_type=(
            self.factor_type
            if hasattr(self, "factor_type")
            else None
        )
        _factor_friendly_name=(
            self.factor_friendly_name
            if hasattr(self, "factor_friendly_name")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _ttl=(
            self.ttl
            if hasattr(self, "ttl")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!r}, "
            f"account_sid={_account_sid!r}, "
            f"service_sid={_service_sid!r}, "
            f"entity_identity={_entity_identity!r}, "
            f"factor_type={_factor_type!r}, "
            f"factor_friendly_name={_factor_friendly_name!r}, "
            f"token={_token!r}, "
            f"url={_url!r}, "
            f"ttl={_ttl!r}, "
            f"date_created={_date_created!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _entity_identity=(
            self.entity_identity
            if hasattr(self, "entity_identity")
            else None
        )
        _factor_type=(
            self.factor_type
            if hasattr(self, "factor_type")
            else None
        )
        _factor_friendly_name=(
            self.factor_friendly_name
            if hasattr(self, "factor_friendly_name")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _ttl=(
            self.ttl
            if hasattr(self, "ttl")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!s}, "
            f"account_sid={_account_sid!s}, "
            f"service_sid={_service_sid!s}, "
            f"entity_identity={_entity_identity!s}, "
            f"factor_type={_factor_type!s}, "
            f"factor_friendly_name={_factor_friendly_name!s}, "
            f"token={_token!s}, "
            f"url={_url!s}, "
            f"ttl={_ttl!s}, "
            f"date_created={_date_created!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
