"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class ApiV2010AccountMessage(object):
    """Implementation of the 'api.v2010.account.message' model.

    Attributes:
        body (str): The text content of the message
        num_segments (str): The number of segments that make up the complete message.
            SMS message bodies that exceed the [character
            limit](https://www.twilio.com/docs/glossary/what-sms-character-limit) are
            segmented and charged as multiple messages. Note: For messages sent via a
            Messaging Service, `num_segments` is initially `0`, since a sender hasn't
            yet been assigned.
        direction (MessageEnumDirection): The direction of the message. Can be:
            `inbound` for incoming messages, `outbound-api` for messages created by
            the REST API, `outbound-call` for messages created during a call, or
            `outbound-reply` for messages created in response to an incoming message.
        mfrom (str): The sender's phone number (in
            [E.164](https://en.wikipedia.org/wiki/E.164) format), [alphanumeric
            sender ID](https://www.twilio.com/docs/sms/quickstart), [Wireless
            SIM](https://www.twilio.com/docs/iot/wireless/programmable-wireless-send-m
            achine-machine-sms-commands), [short
            code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes),
            or  [channel address](https://www.twilio.com/docs/messaging/channels)
            (e.g., `whatsapp:+15554449999`). For incoming messages, this is the
            number or channel address of the sender. For outgoing messages, this
            value is a Twilio phone number, alphanumeric sender ID, short code, or
            channel address from which the message is sent.
        to (str): The recipient's phone number (in
            [E.164](https://en.wikipedia.org/wiki/E.164) format) or [channel
            address](https://www.twilio.com/docs/messaging/channels) (e.g.
            `whatsapp:+15552229999`)
        date_updated (str): The [RFC
            2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message resource was last updated
        price (str): The amount billed for the message in the currency specified by
            `price_unit`. The `price` is populated after the message has been
            sent/received, and may not be immediately availalble. View the [Pricing
            page](https://www.twilio.com/en-us/pricing) for more details.
        error_message (str): The description of the `error_code` if the Message
            `status` is `failed` or `undelivered`. If no error was encountered, the
            value is `null`. The value returned in this field for a specific error
            cause is subject to change as Twilio improves errors. Users should not
            use the `error_code` and `error_message` fields programmatically.
        uri (str): The URI of the Message resource, relative to
            `https://api.twilio.com`.
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) associated with
            the Message resource
        num_media (str): The number of media files associated with the Message
            resource.
        status (VerificationAttemptEnumMessageStatus): The status of the Message.
            Possible values: `accepted`, `scheduled`, `canceled`, `queued`,
            `sending`, `sent`, `failed`, `delivered`, `undelivered`, `receiving`,
            `received`, or `read` (WhatsApp only). For more information, See
            [detailed
            descriptions](https://www.twilio.com/docs/sms/api/message-resource#message
            -status-values).
        messaging_service_sid (str): The SID of the [Messaging
            Service](https://www.twilio.com/docs/messaging/api/service-resource)
            associated with the Message resource. A unique default value is assigned
            if a Messaging Service is not used.
        sid (str): The unique, Twilio-provided string that identifies the Message
            resource.
        date_sent (str): The [RFC
            2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message was sent. For an outgoing message,
            this is when Twilio sent the message. For an incoming message, this is
            when Twilio sent the HTTP request to your incoming message webhook URL.
        date_created (str): The [RFC
            2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message resource was created
        error_code (int): The [error code](https://www.twilio.com/docs/api/errors)
            returned if the Message `status` is `failed` or `undelivered`. If no
            error was encountered, the value is `null`. The value returned in this
            field for a specific error cause is subject to change as Twilio improves
            errors. Users should not use the `error_code` and `error_message` fields
            programmatically.
        price_unit (str): The currency in which `price` is measured, in [ISO
            4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format
            (e.g. `usd`, `eur`, `jpy`).
        api_version (str): The API version used to process the Message
        subresource_uris (Any): A list of related resources identified by their URIs
            relative to `https://api.twilio.com`
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "num_segments": "num_segments",
        "direction": "direction",
        "mfrom": "from",
        "to": "to",
        "date_updated": "date_updated",
        "price": "price",
        "error_message": "error_message",
        "uri": "uri",
        "account_sid": "account_sid",
        "num_media": "num_media",
        "status": "status",
        "messaging_service_sid": "messaging_service_sid",
        "sid": "sid",
        "date_sent": "date_sent",
        "date_created": "date_created",
        "error_code": "error_code",
        "price_unit": "price_unit",
        "api_version": "api_version",
        "subresource_uris": "subresource_uris",
    }

    _optionals = [
        "body",
        "num_segments",
        "direction",
        "mfrom",
        "to",
        "date_updated",
        "price",
        "error_message",
        "uri",
        "account_sid",
        "num_media",
        "status",
        "messaging_service_sid",
        "sid",
        "date_sent",
        "date_created",
        "error_code",
        "price_unit",
        "api_version",
        "subresource_uris",
    ]

    _nullables = [
        "body",
        "num_segments",
        "mfrom",
        "to",
        "date_updated",
        "price",
        "error_message",
        "uri",
        "account_sid",
        "num_media",
        "messaging_service_sid",
        "sid",
        "date_sent",
        "date_created",
        "error_code",
        "price_unit",
        "api_version",
        "subresource_uris",
    ]

    def __init__(
        self,
        body=APIHelper.SKIP,
        num_segments=APIHelper.SKIP,
        direction=APIHelper.SKIP,
        mfrom=APIHelper.SKIP,
        to=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        price=APIHelper.SKIP,
        error_message=APIHelper.SKIP,
        uri=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        num_media=APIHelper.SKIP,
        status=APIHelper.SKIP,
        messaging_service_sid=APIHelper.SKIP,
        sid=APIHelper.SKIP,
        date_sent=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        error_code=APIHelper.SKIP,
        price_unit=APIHelper.SKIP,
        api_version=APIHelper.SKIP,
        subresource_uris=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ApiV2010AccountMessage instance."""
        # Initialize members of the class
        if body is not APIHelper.SKIP:
            self.body = body
        if num_segments is not APIHelper.SKIP:
            self.num_segments = num_segments
        if direction is not APIHelper.SKIP:
            self.direction = direction
        if mfrom is not APIHelper.SKIP:
            self.mfrom = mfrom
        if to is not APIHelper.SKIP:
            self.to = to
        if date_updated is not APIHelper.SKIP:
            self.date_updated = date_updated
        if price is not APIHelper.SKIP:
            self.price = price
        if error_message is not APIHelper.SKIP:
            self.error_message = error_message
        if uri is not APIHelper.SKIP:
            self.uri = uri
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if num_media is not APIHelper.SKIP:
            self.num_media = num_media
        if status is not APIHelper.SKIP:
            self.status = status
        if messaging_service_sid is not APIHelper.SKIP:
            self.messaging_service_sid = messaging_service_sid
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if date_sent is not APIHelper.SKIP:
            self.date_sent = date_sent
        if date_created is not APIHelper.SKIP:
            self.date_created = date_created
        if error_code is not APIHelper.SKIP:
            self.error_code = error_code
        if price_unit is not APIHelper.SKIP:
            self.price_unit = price_unit
        if api_version is not APIHelper.SKIP:
            self.api_version = api_version
        if subresource_uris is not APIHelper.SKIP:
            self.subresource_uris = subresource_uris

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if "body" in dictionary.keys()\
                else APIHelper.SKIP
        num_segments =\
            dictionary.get("num_segments")\
            if "num_segments" in dictionary.keys()\
                else APIHelper.SKIP
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else APIHelper.SKIP
        mfrom =\
            dictionary.get("from")\
            if "from" in dictionary.keys()\
                else APIHelper.SKIP
        to =\
            dictionary.get("to")\
            if "to" in dictionary.keys()\
                else APIHelper.SKIP
        date_updated =\
            dictionary.get("date_updated")\
            if "date_updated" in dictionary.keys()\
                else APIHelper.SKIP
        price =\
            dictionary.get("price")\
            if "price" in dictionary.keys()\
                else APIHelper.SKIP
        error_message =\
            dictionary.get("error_message")\
            if "error_message" in dictionary.keys()\
                else APIHelper.SKIP
        uri =\
            dictionary.get("uri")\
            if "uri" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        num_media =\
            dictionary.get("num_media")\
            if "num_media" in dictionary.keys()\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        messaging_service_sid =\
            dictionary.get("messaging_service_sid")\
            if "messaging_service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        date_sent =\
            dictionary.get("date_sent")\
            if "date_sent" in dictionary.keys()\
                else APIHelper.SKIP
        date_created =\
            dictionary.get("date_created")\
            if "date_created" in dictionary.keys()\
                else APIHelper.SKIP
        error_code =\
            dictionary.get("error_code")\
            if "error_code" in dictionary.keys()\
                else APIHelper.SKIP
        price_unit =\
            dictionary.get("price_unit")\
            if "price_unit" in dictionary.keys()\
                else APIHelper.SKIP
        api_version =\
            dictionary.get("api_version")\
            if "api_version" in dictionary.keys()\
                else APIHelper.SKIP
        subresource_uris =\
            dictionary.get("subresource_uris")\
            if "subresource_uris" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   num_segments,
                   direction,
                   mfrom,
                   to,
                   date_updated,
                   price,
                   error_message,
                   uri,
                   account_sid,
                   num_media,
                   status,
                   messaging_service_sid,
                   sid,
                   date_sent,
                   date_created,
                   error_code,
                   price_unit,
                   api_version,
                   subresource_uris,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _num_segments=(
            self.num_segments
            if hasattr(self, "num_segments")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _mfrom=(
            self.mfrom
            if hasattr(self, "mfrom")
            else None
        )
        _to=(
            self.to
            if hasattr(self, "to")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _error_message=(
            self.error_message
            if hasattr(self, "error_message")
            else None
        )
        _uri=(
            self.uri
            if hasattr(self, "uri")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _num_media=(
            self.num_media
            if hasattr(self, "num_media")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _messaging_service_sid=(
            self.messaging_service_sid
            if hasattr(self, "messaging_service_sid")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _date_sent=(
            self.date_sent
            if hasattr(self, "date_sent")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _error_code=(
            self.error_code
            if hasattr(self, "error_code")
            else None
        )
        _price_unit=(
            self.price_unit
            if hasattr(self, "price_unit")
            else None
        )
        _api_version=(
            self.api_version
            if hasattr(self, "api_version")
            else None
        )
        _subresource_uris=(
            self.subresource_uris
            if hasattr(self, "subresource_uris")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"num_segments={_num_segments!r}, "
            f"direction={_direction!r}, "
            f"mfrom={_mfrom!r}, "
            f"to={_to!r}, "
            f"date_updated={_date_updated!r}, "
            f"price={_price!r}, "
            f"error_message={_error_message!r}, "
            f"uri={_uri!r}, "
            f"account_sid={_account_sid!r}, "
            f"num_media={_num_media!r}, "
            f"status={_status!r}, "
            f"messaging_service_sid={_messaging_service_sid!r}, "
            f"sid={_sid!r}, "
            f"date_sent={_date_sent!r}, "
            f"date_created={_date_created!r}, "
            f"error_code={_error_code!r}, "
            f"price_unit={_price_unit!r}, "
            f"api_version={_api_version!r}, "
            f"subresource_uris={_subresource_uris!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _num_segments=(
            self.num_segments
            if hasattr(self, "num_segments")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _mfrom=(
            self.mfrom
            if hasattr(self, "mfrom")
            else None
        )
        _to=(
            self.to
            if hasattr(self, "to")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _error_message=(
            self.error_message
            if hasattr(self, "error_message")
            else None
        )
        _uri=(
            self.uri
            if hasattr(self, "uri")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _num_media=(
            self.num_media
            if hasattr(self, "num_media")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _messaging_service_sid=(
            self.messaging_service_sid
            if hasattr(self, "messaging_service_sid")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _date_sent=(
            self.date_sent
            if hasattr(self, "date_sent")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _error_code=(
            self.error_code
            if hasattr(self, "error_code")
            else None
        )
        _price_unit=(
            self.price_unit
            if hasattr(self, "price_unit")
            else None
        )
        _api_version=(
            self.api_version
            if hasattr(self, "api_version")
            else None
        )
        _subresource_uris=(
            self.subresource_uris
            if hasattr(self, "subresource_uris")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"num_segments={_num_segments!s}, "
            f"direction={_direction!s}, "
            f"mfrom={_mfrom!s}, "
            f"to={_to!s}, "
            f"date_updated={_date_updated!s}, "
            f"price={_price!s}, "
            f"error_message={_error_message!s}, "
            f"uri={_uri!s}, "
            f"account_sid={_account_sid!s}, "
            f"num_media={_num_media!s}, "
            f"status={_status!s}, "
            f"messaging_service_sid={_messaging_service_sid!s}, "
            f"sid={_sid!s}, "
            f"date_sent={_date_sent!s}, "
            f"date_created={_date_created!s}, "
            f"error_code={_error_code!s}, "
            f"price_unit={_price_unit!s}, "
            f"api_version={_api_version!s}, "
            f"subresource_uris={_subresource_uris!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
