"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class AuthTokenPromotion(object):
    """Implementation of the 'AuthTokenPromotion' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that the secondary
            Auth Token was created for.
        auth_token (str): The promoted Auth Token that must be used to authenticate
            future API requests.
        date_created (datetime): The date and time in UTC when the resource was
            created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        date_updated (datetime): The date and time in GMT when the resource was last
            updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        url (str): The URI for this resource, relative to
            `https://accounts.twilio.com`
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "auth_token": "auth_token",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "auth_token",
        "date_created",
        "date_updated",
        "url",
    ]

    _nullables = [
        "account_sid",
        "auth_token",
        "date_created",
        "date_updated",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        auth_token=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AuthTokenPromotion instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if auth_token is not APIHelper.SKIP:
            self.auth_token = auth_token
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        auth_token =\
            dictionary.get("auth_token")\
            if "auth_token" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   auth_token,
                   date_created,
                   date_updated,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _auth_token=(
            self.auth_token
            if hasattr(self, "auth_token")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"auth_token={_auth_token!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _auth_token=(
            self.auth_token
            if hasattr(self, "auth_token")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"auth_token={_auth_token!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
