"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class Bucket(object):
    """Implementation of the 'Bucket' model.

    Attributes:
        sid (str): A 34 character string that uniquely identifies this Bucket.
        rate_limit_sid (str): The Twilio-provided string that uniquely identifies the
            Rate Limit resource.
        service_sid (str): The SID of the
            [Service](https://www.twilio.com/docs/verify/api/service) the resource is
            associated with.
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            Rate Limit resource.
        max (int): Maximum number of requests permitted in during the interval.
        interval (int): Number of seconds that the rate limit will be enforced over.
        date_created (datetime): The date and time in GMT when the resource was
            created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt)
            format.
        date_updated (datetime): The date and time in GMT when the resource was last
            updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt)
            format.
        url (str): The URL of this resource.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sid": "sid",
        "rate_limit_sid": "rate_limit_sid",
        "service_sid": "service_sid",
        "account_sid": "account_sid",
        "max": "max",
        "interval": "interval",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "url": "url",
    }

    _optionals = [
        "sid",
        "rate_limit_sid",
        "service_sid",
        "account_sid",
        "max",
        "interval",
        "date_created",
        "date_updated",
        "url",
    ]

    _nullables = [
        "sid",
        "rate_limit_sid",
        "service_sid",
        "account_sid",
        "date_created",
        "date_updated",
        "url",
    ]

    def __init__(
        self,
        sid=APIHelper.SKIP,
        rate_limit_sid=APIHelper.SKIP,
        service_sid=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        max=0,
        interval=0,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Bucket instance."""
        # Initialize members of the class
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if rate_limit_sid is not APIHelper.SKIP:
            self.rate_limit_sid = rate_limit_sid
        if service_sid is not APIHelper.SKIP:
            self.service_sid = service_sid
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        self.max = max
        self.interval = interval
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        rate_limit_sid =\
            dictionary.get("rate_limit_sid")\
            if "rate_limit_sid" in dictionary.keys()\
                else APIHelper.SKIP
        service_sid =\
            dictionary.get("service_sid")\
            if "service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        max =\
            dictionary.get("max")\
            if dictionary.get("max")\
                else 0
        interval =\
            dictionary.get("interval")\
            if dictionary.get("interval")\
                else 0
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sid,
                   rate_limit_sid,
                   service_sid,
                   account_sid,
                   max,
                   interval,
                   date_created,
                   date_updated,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _rate_limit_sid=(
            self.rate_limit_sid
            if hasattr(self, "rate_limit_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _max=(
            self.max
            if hasattr(self, "max")
            else None
        )
        _interval=(
            self.interval
            if hasattr(self, "interval")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!r}, "
            f"rate_limit_sid={_rate_limit_sid!r}, "
            f"service_sid={_service_sid!r}, "
            f"account_sid={_account_sid!r}, "
            f"max={_max!r}, "
            f"interval={_interval!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _rate_limit_sid=(
            self.rate_limit_sid
            if hasattr(self, "rate_limit_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _max=(
            self.max
            if hasattr(self, "max")
            else None
        )
        _interval=(
            self.interval
            if hasattr(self, "interval")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!s}, "
            f"rate_limit_sid={_rate_limit_sid!s}, "
            f"service_sid={_service_sid!s}, "
            f"account_sid={_account_sid!s}, "
            f"max={_max!s}, "
            f"interval={_interval!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
