"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class BulkContacts(object):
    """Implementation of the 'BulkContacts' model.

    Attributes:
        items (Any): A list of objects where each object represents the result of
            processing a `correlation_id`. Each object contains the following fields:
            `correlation_id`, a unique 32-character UUID that maps the response to
            the original request; `error_code`, an integer where 0 indicates success
            and any non-zero value represents an error; and `error_messages`, an
            array of strings describing specific validation errors encountered. If
            the request is successful, the error_messages array will be empty.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "items": "items",
    }

    _optionals = [
        "items",
    ]

    _nullables = [
        "items",
    ]

    def __init__(
        self,
        items=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BulkContacts instance."""
        # Initialize members of the class
        if items is not APIHelper.SKIP:
            self.items = items

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        items =\
            dictionary.get("items")\
            if "items" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(items,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _items=(
            self.items
            if hasattr(self, "items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"items={_items!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _items=(
            self.items
            if hasattr(self, "items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"items={_items!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
