"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ChallengeEnumChallengeStatuses(object):
    """Implementation of the 'ChallengeEnumChallengeStatuses' enum.

    The Status of this Challenge. One of `pending`, `expired`, `approved` or `denied`.

    Attributes:
        PENDING: The enum member of type str.
        EXPIRED: The enum member of type str.
        APPROVED: The enum member of type str.
        DENIED: The enum member of type str.

    """

    PENDING = "pending"

    EXPIRED = "expired"

    APPROVED = "approved"

    DENIED = "denied"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
