"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class Configuration(object):
    """Implementation of the 'Configuration' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) responsible for
            this configuration.
        default_chat_service_sid (str): The SID of the default [Conversation
            Service](https://www.twilio.com/docs/conversations/api/service-resource)
            used when creating a conversation.
        default_messaging_service_sid (str): The SID of the default [Messaging
            Service](https://www.twilio.com/docs/messaging/api/service-resource) used
            when creating a conversation.
        default_inactive_timer (str): Default ISO8601 duration when conversation will
            be switched to `inactive` state. Minimum value for this timer is 1 minute.
        default_closed_timer (str): Default ISO8601 duration when conversation will
            be switched to `closed` state. Minimum value for this timer is 10 minutes.
        url (str): An absolute API resource URL for this global configuration.
        links (Any): Contains absolute API resource URLs to access the webhook and
            default service configurations.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "default_chat_service_sid": "default_chat_service_sid",
        "default_messaging_service_sid": "default_messaging_service_sid",
        "default_inactive_timer": "default_inactive_timer",
        "default_closed_timer": "default_closed_timer",
        "url": "url",
        "links": "links",
    }

    _optionals = [
        "account_sid",
        "default_chat_service_sid",
        "default_messaging_service_sid",
        "default_inactive_timer",
        "default_closed_timer",
        "url",
        "links",
    ]

    _nullables = [
        "account_sid",
        "default_chat_service_sid",
        "default_messaging_service_sid",
        "default_inactive_timer",
        "default_closed_timer",
        "url",
        "links",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        default_chat_service_sid=APIHelper.SKIP,
        default_messaging_service_sid=APIHelper.SKIP,
        default_inactive_timer=APIHelper.SKIP,
        default_closed_timer=APIHelper.SKIP,
        url=APIHelper.SKIP,
        links=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Configuration instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if default_chat_service_sid is not APIHelper.SKIP:
            self.default_chat_service_sid = default_chat_service_sid
        if default_messaging_service_sid is not APIHelper.SKIP:
            self.default_messaging_service_sid = default_messaging_service_sid
        if default_inactive_timer is not APIHelper.SKIP:
            self.default_inactive_timer = default_inactive_timer
        if default_closed_timer is not APIHelper.SKIP:
            self.default_closed_timer = default_closed_timer
        if url is not APIHelper.SKIP:
            self.url = url
        if links is not APIHelper.SKIP:
            self.links = links

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        default_chat_service_sid =\
            dictionary.get("default_chat_service_sid")\
            if "default_chat_service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        default_messaging_service_sid =\
            dictionary.get("default_messaging_service_sid")\
            if "default_messaging_service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        default_inactive_timer =\
            dictionary.get("default_inactive_timer")\
            if "default_inactive_timer" in dictionary.keys()\
                else APIHelper.SKIP
        default_closed_timer =\
            dictionary.get("default_closed_timer")\
            if "default_closed_timer" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        links =\
            dictionary.get("links")\
            if "links" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   default_chat_service_sid,
                   default_messaging_service_sid,
                   default_inactive_timer,
                   default_closed_timer,
                   url,
                   links,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _default_chat_service_sid=(
            self.default_chat_service_sid
            if hasattr(self, "default_chat_service_sid")
            else None
        )
        _default_messaging_service_sid=(
            self.default_messaging_service_sid
            if hasattr(self, "default_messaging_service_sid")
            else None
        )
        _default_inactive_timer=(
            self.default_inactive_timer
            if hasattr(self, "default_inactive_timer")
            else None
        )
        _default_closed_timer=(
            self.default_closed_timer
            if hasattr(self, "default_closed_timer")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"default_chat_service_sid={_default_chat_service_sid!r}, "
            f"default_messaging_service_sid={_default_messaging_service_sid!r}, "
            f"default_inactive_timer={_default_inactive_timer!r}, "
            f"default_closed_timer={_default_closed_timer!r}, "
            f"url={_url!r}, "
            f"links={_links!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _default_chat_service_sid=(
            self.default_chat_service_sid
            if hasattr(self, "default_chat_service_sid")
            else None
        )
        _default_messaging_service_sid=(
            self.default_messaging_service_sid
            if hasattr(self, "default_messaging_service_sid")
            else None
        )
        _default_inactive_timer=(
            self.default_inactive_timer
            if hasattr(self, "default_inactive_timer")
            else None
        )
        _default_closed_timer=(
            self.default_closed_timer
            if hasattr(self, "default_closed_timer")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"default_chat_service_sid={_default_chat_service_sid!s}, "
            f"default_messaging_service_sid={_default_messaging_service_sid!s}, "
            f"default_inactive_timer={_default_inactive_timer!s}, "
            f"default_closed_timer={_default_closed_timer!s}, "
            f"url={_url!s}, "
            f"links={_links!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
