"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class ConfigurationWebhook(object):
    """Implementation of the 'ConfigurationWebhook' model.

    Attributes:
        account_sid (str): The unique ID of the
            [Account](https://www.twilio.com/docs/iam/api/account) responsible for
            this conversation.
        method (ConfigurationWebhookMethod): The HTTP method to be used when sending
            a webhook request.
        filters (List[str]): The list of webhook event triggers that are enabled for
            this Service: `onMessageAdded`, `onMessageUpdated`, `onMessageRemoved`,
            `onMessageAdd`, `onMessageUpdate`, `onMessageRemove`,
            `onConversationUpdated`, `onConversationRemoved`, `onConversationAdd`,
            `onConversationAdded`, `onConversationRemove`, `onConversationUpdate`,
            `onConversationStateUpdated`, `onParticipantAdded`,
            `onParticipantUpdated`, `onParticipantRemoved`, `onParticipantAdd`,
            `onParticipantRemove`, `onParticipantUpdate`, `onDeliveryUpdated`,
            `onUserAdded`, `onUserUpdate`, `onUserUpdated`
        pre_webhook_url (str): The absolute url the pre-event webhook request should
            be sent to.
        post_webhook_url (str): The absolute url the post-event webhook request
            should be sent to.
        target (ConfigurationWebhookTarget): The routing target of the webhook. Can
            be ordinary or route internally to Flex
        url (str): An absolute API resource API resource URL for this webhook.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "method": "method",
        "filters": "filters",
        "pre_webhook_url": "pre_webhook_url",
        "post_webhook_url": "post_webhook_url",
        "target": "target",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "method",
        "filters",
        "pre_webhook_url",
        "post_webhook_url",
        "target",
        "url",
    ]

    _nullables = [
        "account_sid",
        "filters",
        "pre_webhook_url",
        "post_webhook_url",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        method=APIHelper.SKIP,
        filters=APIHelper.SKIP,
        pre_webhook_url=APIHelper.SKIP,
        post_webhook_url=APIHelper.SKIP,
        target=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ConfigurationWebhook instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if method is not APIHelper.SKIP:
            self.method = method
        if filters is not APIHelper.SKIP:
            self.filters = filters
        if pre_webhook_url is not APIHelper.SKIP:
            self.pre_webhook_url = pre_webhook_url
        if post_webhook_url is not APIHelper.SKIP:
            self.post_webhook_url = post_webhook_url
        if target is not APIHelper.SKIP:
            self.target = target
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        method =\
            dictionary.get("method")\
            if dictionary.get("method")\
                else APIHelper.SKIP
        filters =\
            dictionary.get("filters")\
            if "filters" in dictionary.keys()\
                else APIHelper.SKIP
        pre_webhook_url =\
            dictionary.get("pre_webhook_url")\
            if "pre_webhook_url" in dictionary.keys()\
                else APIHelper.SKIP
        post_webhook_url =\
            dictionary.get("post_webhook_url")\
            if "post_webhook_url" in dictionary.keys()\
                else APIHelper.SKIP
        target =\
            dictionary.get("target")\
            if dictionary.get("target")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   method,
                   filters,
                   pre_webhook_url,
                   post_webhook_url,
                   target,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _method=(
            self.method
            if hasattr(self, "method")
            else None
        )
        _filters=(
            self.filters
            if hasattr(self, "filters")
            else None
        )
        _pre_webhook_url=(
            self.pre_webhook_url
            if hasattr(self, "pre_webhook_url")
            else None
        )
        _post_webhook_url=(
            self.post_webhook_url
            if hasattr(self, "post_webhook_url")
            else None
        )
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"method={_method!r}, "
            f"filters={_filters!r}, "
            f"pre_webhook_url={_pre_webhook_url!r}, "
            f"post_webhook_url={_post_webhook_url!r}, "
            f"target={_target!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _method=(
            self.method
            if hasattr(self, "method")
            else None
        )
        _filters=(
            self.filters
            if hasattr(self, "filters")
            else None
        )
        _pre_webhook_url=(
            self.pre_webhook_url
            if hasattr(self, "pre_webhook_url")
            else None
        )
        _post_webhook_url=(
            self.post_webhook_url
            if hasattr(self, "post_webhook_url")
            else None
        )
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"method={_method!s}, "
            f"filters={_filters!s}, "
            f"pre_webhook_url={_pre_webhook_url!s}, "
            f"post_webhook_url={_post_webhook_url!s}, "
            f"target={_target!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
