"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ConfigurationAddressType(object):
    """Implementation of the 'ConfigurationAddressType' enum.

    Type of Address, value can be `whatsapp` or `sms`.

    Attributes:
        SMS: The enum member of type str.
        WHATSAPP: The enum member of type str.
        MESSENGER: The enum member of type str.
        GBM: The enum member of type str.
        EMAIL: The enum member of type str.
        RCS: The enum member of type str.
        APPLE: The enum member of type str.
        CHAT: The enum member of type str.

    """

    SMS = "sms"

    WHATSAPP = "whatsapp"

    MESSENGER = "messenger"

    GBM = "gbm"

    EMAIL = "email"

    RCS = "rcs"

    APPLE = "apple"

    CHAT = "chat"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
