"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ConversationScopedWebhookTarget(object):
    """Implementation of the 'ConversationScopedWebhookTarget' enum.

    The target of this webhook: `webhook`, `studio`, `trigger`

    Attributes:
        WEBHOOK: The enum member of type str.
        TRIGGER: The enum member of type str.
        STUDIO: The enum member of type str.

    """

    WEBHOOK = "webhook"

    TRIGGER = "trigger"

    STUDIO = "studio"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
