"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class ConversationScopedWebhook(object):
    """Implementation of the 'ConversationScopedWebhook' model.

    Attributes:
        sid (str): A 34 character string that uniquely identifies this resource.
        account_sid (str): The unique ID of the
            [Account](https://www.twilio.com/docs/iam/api/account) responsible for
            this conversation.
        conversation_sid (str): The unique ID of the
            [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
            resource) for this webhook.
        target (str): The target of this webhook: `webhook`, `studio`, `trigger`
        url (str): An absolute API resource URL for this webhook.
        configuration (Any): The configuration of this webhook. Is defined based on
            target.
        date_created (datetime): The date that this resource was created.
        date_updated (datetime): The date that this resource was last updated.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sid": "sid",
        "account_sid": "account_sid",
        "conversation_sid": "conversation_sid",
        "target": "target",
        "url": "url",
        "configuration": "configuration",
        "date_created": "date_created",
        "date_updated": "date_updated",
    }

    _optionals = [
        "sid",
        "account_sid",
        "conversation_sid",
        "target",
        "url",
        "configuration",
        "date_created",
        "date_updated",
    ]

    _nullables = [
        "sid",
        "account_sid",
        "conversation_sid",
        "target",
        "url",
        "configuration",
        "date_created",
        "date_updated",
    ]

    def __init__(
        self,
        sid=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        conversation_sid=APIHelper.SKIP,
        target=APIHelper.SKIP,
        url=APIHelper.SKIP,
        configuration=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ConversationScopedWebhook instance."""
        # Initialize members of the class
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if conversation_sid is not APIHelper.SKIP:
            self.conversation_sid = conversation_sid
        if target is not APIHelper.SKIP:
            self.target = target
        if url is not APIHelper.SKIP:
            self.url = url
        if configuration is not APIHelper.SKIP:
            self.configuration = configuration
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        conversation_sid =\
            dictionary.get("conversation_sid")\
            if "conversation_sid" in dictionary.keys()\
                else APIHelper.SKIP
        target =\
            dictionary.get("target")\
            if "target" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        configuration =\
            dictionary.get("configuration")\
            if "configuration" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sid,
                   account_sid,
                   conversation_sid,
                   target,
                   url,
                   configuration,
                   date_created,
                   date_updated,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _conversation_sid=(
            self.conversation_sid
            if hasattr(self, "conversation_sid")
            else None
        )
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!r}, "
            f"account_sid={_account_sid!r}, "
            f"conversation_sid={_conversation_sid!r}, "
            f"target={_target!r}, "
            f"url={_url!r}, "
            f"configuration={_configuration!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _conversation_sid=(
            self.conversation_sid
            if hasattr(self, "conversation_sid")
            else None
        )
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!s}, "
            f"account_sid={_account_sid!s}, "
            f"conversation_sid={_conversation_sid!s}, "
            f"target={_target!s}, "
            f"url={_url!s}, "
            f"configuration={_configuration!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
