"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class Entity(object):
    """Implementation of the 'Entity' model.

    Attributes:
        sid (str): A 34 character string that uniquely identifies this Entity.
        identity (str): The unique external identifier for the Entity of the Service.
            This identifier should be immutable, not PII, length between 8 and 64
            characters, and generated by your external system, such as your user's
            UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric
            characters.
        account_sid (str): The unique SID identifier of the Account.
        service_sid (str): The unique SID identifier of the Service.
        date_created (datetime): The date that this Entity was created, given in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        date_updated (datetime): The date that this Entity was updated, given in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        url (str): The URL of this resource.
        links (Any): Contains a dictionary of URL links to nested resources of this
            Entity.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sid": "sid",
        "identity": "identity",
        "account_sid": "account_sid",
        "service_sid": "service_sid",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "url": "url",
        "links": "links",
    }

    _optionals = [
        "sid",
        "identity",
        "account_sid",
        "service_sid",
        "date_created",
        "date_updated",
        "url",
        "links",
    ]

    _nullables = [
        "sid",
        "identity",
        "account_sid",
        "service_sid",
        "date_created",
        "date_updated",
        "url",
        "links",
    ]

    def __init__(
        self,
        sid=APIHelper.SKIP,
        identity=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        service_sid=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        url=APIHelper.SKIP,
        links=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Entity instance."""
        # Initialize members of the class
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if identity is not APIHelper.SKIP:
            self.identity = identity
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if service_sid is not APIHelper.SKIP:
            self.service_sid = service_sid
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if url is not APIHelper.SKIP:
            self.url = url
        if links is not APIHelper.SKIP:
            self.links = links

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        identity =\
            dictionary.get("identity")\
            if "identity" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        service_sid =\
            dictionary.get("service_sid")\
            if "service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        links =\
            dictionary.get("links")\
            if "links" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sid,
                   identity,
                   account_sid,
                   service_sid,
                   date_created,
                   date_updated,
                   url,
                   links,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _identity=(
            self.identity
            if hasattr(self, "identity")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!r}, "
            f"identity={_identity!r}, "
            f"account_sid={_account_sid!r}, "
            f"service_sid={_service_sid!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"url={_url!r}, "
            f"links={_links!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _identity=(
            self.identity
            if hasattr(self, "identity")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _service_sid=(
            self.service_sid
            if hasattr(self, "service_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!s}, "
            f"identity={_identity!s}, "
            f"account_sid={_account_sid!s}, "
            f"service_sid={_service_sid!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"url={_url!s}, "
            f"links={_links!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
