"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper
from twilioapis.models.configuration_address import (
    ConfigurationAddress,
)
from twilioapis.models.meta import Meta


class ListConfigurationAddressResponse(object):
    """Implementation of the 'ListConfigurationAddressResponse' model.

    Attributes:
        address_configurations (List[ConfigurationAddress]): The model property of
            type List[ConfigurationAddress].
        meta (Meta): The model property of type Meta.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address_configurations": "address_configurations",
        "meta": "meta",
    }

    _optionals = [
        "address_configurations",
        "meta",
    ]

    def __init__(
        self,
        address_configurations=APIHelper.SKIP,
        meta=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListConfigurationAddressResponse instance."""
        # Initialize members of the class
        if address_configurations is not APIHelper.SKIP:
            self.address_configurations = address_configurations
        if meta is not APIHelper.SKIP:
            self.meta = meta

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address_configurations = None
        if dictionary.get("address_configurations") is not None:
            address_configurations = [
                ConfigurationAddress.from_dictionary(x)
                    for x in dictionary.get("address_configurations")
            ]
        else:
            address_configurations = APIHelper.SKIP
        meta =\
            Meta.from_dictionary(
                dictionary.get("meta"))\
                if "meta" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(address_configurations,
                   meta,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address_configurations=(
            self.address_configurations
            if hasattr(self, "address_configurations")
            else None
        )
        _meta=(
            self.meta
            if hasattr(self, "meta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address_configurations={_address_configurations!r}, "
            f"meta={_meta!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address_configurations=(
            self.address_configurations
            if hasattr(self, "address_configurations")
            else None
        )
        _meta=(
            self.meta
            if hasattr(self, "meta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address_configurations={_address_configurations!s}, "
            f"meta={_meta!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
