"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class NotifPriority(object):
    """Implementation of the 'NotifPriority' enum.

    The priority of the notification. Can be: `low` or `high` and the default is
    `high`. A value of `low` optimizes the client app's battery consumption; however,
    notifications may be delivered with unspecified delay. For FCM and GCM, `low`
    priority is the same as `Normal` priority. For APNS `low` priority is the same as
    `5`. A value of `high` sends the notification immediately, and can wake up a
    sleeping device. For FCM and GCM, `high` is the same as `High` priority. For
    APNS, `high` is a priority `10`. SMS does not support this property.

    Attributes:
        HIGH: The enum member of type str.
        LOW: The enum member of type str.

    """

    HIGH = "high"

    LOW = "low"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
