"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ServiceBindingBindingType(object):
    """Implementation of the 'ServiceBindingBindingType' enum.

    The push technology to use for the Binding. Can be: `apn`, `gcm`, `fcm`, or
    `twilsock`.  See [push notification
    configuration](https://www.twilio.com/docs/chat/push-notification-configuration)
    for more info.

    Attributes:
        APN: The enum member of type str.
        GCM: The enum member of type str.
        FCM: The enum member of type str.
        TWILSOCK: The enum member of type str.

    """

    APN = "apn"

    GCM = "gcm"

    FCM = "fcm"

    TWILSOCK = "twilsock"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
