"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class ServiceNotification(object):
    """Implementation of the 'ServiceNotification' model.

    Attributes:
        account_sid (str): The unique ID of the
            [Account](https://www.twilio.com/docs/iam/api/account) responsible for
            this configuration.
        chat_service_sid (str): The SID of the [Conversation
            Service](https://www.twilio.com/docs/conversations/api/service-resource)
            the Configuration applies to.
        new_message (Any): The Push Notification configuration for New Messages.
        added_to_conversation (Any): The Push Notification configuration for being
            added to a Conversation.
        removed_from_conversation (Any): The Push Notification configuration for
            being removed from a Conversation.
        log_enabled (bool): Weather the notification logging is enabled.
        url (str): An absolute API resource URL for this configuration.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "chat_service_sid": "chat_service_sid",
        "new_message": "new_message",
        "added_to_conversation": "added_to_conversation",
        "removed_from_conversation": "removed_from_conversation",
        "log_enabled": "log_enabled",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "chat_service_sid",
        "new_message",
        "added_to_conversation",
        "removed_from_conversation",
        "log_enabled",
        "url",
    ]

    _nullables = [
        "account_sid",
        "chat_service_sid",
        "new_message",
        "added_to_conversation",
        "removed_from_conversation",
        "log_enabled",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        chat_service_sid=APIHelper.SKIP,
        new_message=APIHelper.SKIP,
        added_to_conversation=APIHelper.SKIP,
        removed_from_conversation=APIHelper.SKIP,
        log_enabled=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServiceNotification instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if chat_service_sid is not APIHelper.SKIP:
            self.chat_service_sid = chat_service_sid
        if new_message is not APIHelper.SKIP:
            self.new_message = new_message
        if added_to_conversation is not APIHelper.SKIP:
            self.added_to_conversation = added_to_conversation
        if removed_from_conversation is not APIHelper.SKIP:
            self.removed_from_conversation = removed_from_conversation
        if log_enabled is not APIHelper.SKIP:
            self.log_enabled = log_enabled
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        chat_service_sid =\
            dictionary.get("chat_service_sid")\
            if "chat_service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        new_message =\
            dictionary.get("new_message")\
            if "new_message" in dictionary.keys()\
                else APIHelper.SKIP
        added_to_conversation =\
            dictionary.get("added_to_conversation")\
            if "added_to_conversation" in dictionary.keys()\
                else APIHelper.SKIP
        removed_from_conversation =\
            dictionary.get("removed_from_conversation")\
            if "removed_from_conversation" in dictionary.keys()\
                else APIHelper.SKIP
        log_enabled =\
            dictionary.get("log_enabled")\
            if "log_enabled" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   chat_service_sid,
                   new_message,
                   added_to_conversation,
                   removed_from_conversation,
                   log_enabled,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _chat_service_sid=(
            self.chat_service_sid
            if hasattr(self, "chat_service_sid")
            else None
        )
        _new_message=(
            self.new_message
            if hasattr(self, "new_message")
            else None
        )
        _added_to_conversation=(
            self.added_to_conversation
            if hasattr(self, "added_to_conversation")
            else None
        )
        _removed_from_conversation=(
            self.removed_from_conversation
            if hasattr(self, "removed_from_conversation")
            else None
        )
        _log_enabled=(
            self.log_enabled
            if hasattr(self, "log_enabled")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"chat_service_sid={_chat_service_sid!r}, "
            f"new_message={_new_message!r}, "
            f"added_to_conversation={_added_to_conversation!r}, "
            f"removed_from_conversation={_removed_from_conversation!r}, "
            f"log_enabled={_log_enabled!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _chat_service_sid=(
            self.chat_service_sid
            if hasattr(self, "chat_service_sid")
            else None
        )
        _new_message=(
            self.new_message
            if hasattr(self, "new_message")
            else None
        )
        _added_to_conversation=(
            self.added_to_conversation
            if hasattr(self, "added_to_conversation")
            else None
        )
        _removed_from_conversation=(
            self.removed_from_conversation
            if hasattr(self, "removed_from_conversation")
            else None
        )
        _log_enabled=(
            self.log_enabled
            if hasattr(self, "log_enabled")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"chat_service_sid={_chat_service_sid!s}, "
            f"new_message={_new_message!s}, "
            f"added_to_conversation={_added_to_conversation!s}, "
            f"removed_from_conversation={_removed_from_conversation!s}, "
            f"log_enabled={_log_enabled!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
