"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class ServiceBinding(object):
    """Implementation of the 'ServiceBinding' model.

    Attributes:
        sid (str): A 34 character string that uniquely identifies this resource.
        account_sid (str): The unique ID of the
            [Account](https://www.twilio.com/docs/iam/api/account) responsible for
            this binding.
        chat_service_sid (str): The SID of the [Conversation
            Service](https://www.twilio.com/docs/conversations/api/service-resource)
            the Binding resource is associated with.
        credential_sid (str): The SID of the
            [Credential](https://www.twilio.com/docs/conversations/api/credential-reso
            urce) for the binding. See [push notification
            configuration](https://www.twilio.com/docs/chat/push-notification-configur
            ation) for more info.
        date_created (datetime): The date that this resource was created.
        date_updated (datetime): The date that this resource was last updated.
        endpoint (str): The unique endpoint identifier for the Binding. The format of
            this value depends on the `binding_type`.
        identity (str): The application-defined string that uniquely identifies the
            [Conversation
            User](https://www.twilio.com/docs/conversations/api/user-resource) within
            the [Conversation
            Service](https://www.twilio.com/docs/conversations/api/service-resource).
            See [access
            tokens](https://www.twilio.com/docs/conversations/create-tokens) for more
            info.
        binding_type (ServiceBindingBindingType): The push technology to use for the
            Binding. Can be: `apn`, `gcm`, `fcm`, or `twilsock`.  See [push
            notification
            configuration](https://www.twilio.com/docs/chat/push-notification-configur
            ation) for more info.
        message_types (List[str]): The [Conversation message
            types](https://www.twilio.com/docs/chat/push-notification-configuration#pu
            sh-types) the binding is subscribed to.
        url (str): An absolute API resource URL for this binding.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sid": "sid",
        "account_sid": "account_sid",
        "chat_service_sid": "chat_service_sid",
        "credential_sid": "credential_sid",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "endpoint": "endpoint",
        "identity": "identity",
        "binding_type": "binding_type",
        "message_types": "message_types",
        "url": "url",
    }

    _optionals = [
        "sid",
        "account_sid",
        "chat_service_sid",
        "credential_sid",
        "date_created",
        "date_updated",
        "endpoint",
        "identity",
        "binding_type",
        "message_types",
        "url",
    ]

    _nullables = [
        "sid",
        "account_sid",
        "chat_service_sid",
        "credential_sid",
        "date_created",
        "date_updated",
        "endpoint",
        "identity",
        "message_types",
        "url",
    ]

    def __init__(
        self,
        sid=APIHelper.SKIP,
        account_sid=APIHelper.SKIP,
        chat_service_sid=APIHelper.SKIP,
        credential_sid=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        endpoint=APIHelper.SKIP,
        identity=APIHelper.SKIP,
        binding_type=APIHelper.SKIP,
        message_types=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServiceBinding instance."""
        # Initialize members of the class
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if chat_service_sid is not APIHelper.SKIP:
            self.chat_service_sid = chat_service_sid
        if credential_sid is not APIHelper.SKIP:
            self.credential_sid = credential_sid
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if endpoint is not APIHelper.SKIP:
            self.endpoint = endpoint
        if identity is not APIHelper.SKIP:
            self.identity = identity
        if binding_type is not APIHelper.SKIP:
            self.binding_type = binding_type
        if message_types is not APIHelper.SKIP:
            self.message_types = message_types
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        chat_service_sid =\
            dictionary.get("chat_service_sid")\
            if "chat_service_sid" in dictionary.keys()\
                else APIHelper.SKIP
        credential_sid =\
            dictionary.get("credential_sid")\
            if "credential_sid" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        endpoint =\
            dictionary.get("endpoint")\
            if "endpoint" in dictionary.keys()\
                else APIHelper.SKIP
        identity =\
            dictionary.get("identity")\
            if "identity" in dictionary.keys()\
                else APIHelper.SKIP
        binding_type =\
            dictionary.get("binding_type")\
            if dictionary.get("binding_type")\
                else APIHelper.SKIP
        message_types =\
            dictionary.get("message_types")\
            if "message_types" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sid,
                   account_sid,
                   chat_service_sid,
                   credential_sid,
                   date_created,
                   date_updated,
                   endpoint,
                   identity,
                   binding_type,
                   message_types,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _chat_service_sid=(
            self.chat_service_sid
            if hasattr(self, "chat_service_sid")
            else None
        )
        _credential_sid=(
            self.credential_sid
            if hasattr(self, "credential_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _endpoint=(
            self.endpoint
            if hasattr(self, "endpoint")
            else None
        )
        _identity=(
            self.identity
            if hasattr(self, "identity")
            else None
        )
        _binding_type=(
            self.binding_type
            if hasattr(self, "binding_type")
            else None
        )
        _message_types=(
            self.message_types
            if hasattr(self, "message_types")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!r}, "
            f"account_sid={_account_sid!r}, "
            f"chat_service_sid={_chat_service_sid!r}, "
            f"credential_sid={_credential_sid!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"endpoint={_endpoint!r}, "
            f"identity={_identity!r}, "
            f"binding_type={_binding_type!r}, "
            f"message_types={_message_types!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _chat_service_sid=(
            self.chat_service_sid
            if hasattr(self, "chat_service_sid")
            else None
        )
        _credential_sid=(
            self.credential_sid
            if hasattr(self, "credential_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _endpoint=(
            self.endpoint
            if hasattr(self, "endpoint")
            else None
        )
        _identity=(
            self.identity
            if hasattr(self, "identity")
            else None
        )
        _binding_type=(
            self.binding_type
            if hasattr(self, "binding_type")
            else None
        )
        _message_types=(
            self.message_types
            if hasattr(self, "message_types")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sid={_sid!s}, "
            f"account_sid={_account_sid!s}, "
            f"chat_service_sid={_chat_service_sid!s}, "
            f"credential_sid={_credential_sid!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"endpoint={_endpoint!s}, "
            f"identity={_identity!s}, "
            f"binding_type={_binding_type!s}, "
            f"message_types={_message_types!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
