"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class TaskQueueStatistics(object):
    """Implementation of the 'TaskQueueStatistics' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            TaskQueue resource.
        cumulative (Any): An object that contains the cumulative statistics for the
            TaskQueue.
        realtime (Any): An object that contains the real-time statistics for the
            TaskQueue.
        task_queue_sid (str): The SID of the TaskQueue from which these statistics
            were calculated.
        workspace_sid (str): The SID of the Workspace that contains the TaskQueue.
        url (str): The absolute URL of the TaskQueue statistics resource.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "cumulative": "cumulative",
        "realtime": "realtime",
        "task_queue_sid": "task_queue_sid",
        "workspace_sid": "workspace_sid",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "cumulative",
        "realtime",
        "task_queue_sid",
        "workspace_sid",
        "url",
    ]

    _nullables = [
        "account_sid",
        "cumulative",
        "realtime",
        "task_queue_sid",
        "workspace_sid",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        cumulative=APIHelper.SKIP,
        realtime=APIHelper.SKIP,
        task_queue_sid=APIHelper.SKIP,
        workspace_sid=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TaskQueueStatistics instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if cumulative is not APIHelper.SKIP:
            self.cumulative = cumulative
        if realtime is not APIHelper.SKIP:
            self.realtime = realtime
        if task_queue_sid is not APIHelper.SKIP:
            self.task_queue_sid = task_queue_sid
        if workspace_sid is not APIHelper.SKIP:
            self.workspace_sid = workspace_sid
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        cumulative =\
            dictionary.get("cumulative")\
            if "cumulative" in dictionary.keys()\
                else APIHelper.SKIP
        realtime =\
            dictionary.get("realtime")\
            if "realtime" in dictionary.keys()\
                else APIHelper.SKIP
        task_queue_sid =\
            dictionary.get("task_queue_sid")\
            if "task_queue_sid" in dictionary.keys()\
                else APIHelper.SKIP
        workspace_sid =\
            dictionary.get("workspace_sid")\
            if "workspace_sid" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   cumulative,
                   realtime,
                   task_queue_sid,
                   workspace_sid,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _cumulative=(
            self.cumulative
            if hasattr(self, "cumulative")
            else None
        )
        _realtime=(
            self.realtime
            if hasattr(self, "realtime")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"cumulative={_cumulative!r}, "
            f"realtime={_realtime!r}, "
            f"task_queue_sid={_task_queue_sid!r}, "
            f"workspace_sid={_workspace_sid!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _cumulative=(
            self.cumulative
            if hasattr(self, "cumulative")
            else None
        )
        _realtime=(
            self.realtime
            if hasattr(self, "realtime")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"cumulative={_cumulative!s}, "
            f"realtime={_realtime!s}, "
            f"task_queue_sid={_task_queue_sid!s}, "
            f"workspace_sid={_workspace_sid!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
