"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TaskReservationConferenceEvent(object):
    """Implementation of the 'TaskReservationConferenceEvent' enum.

    Attributes:
        START: The enum member of type str.
        END: The enum member of type str.
        JOIN: The enum member of type str.
        LEAVE: The enum member of type str.
        MUTE: The enum member of type str.
        HOLD: The enum member of type str.
        SPEAKER: The enum member of type str.

    """

    START = "start"

    END = "end"

    JOIN = "join"

    LEAVE = "leave"

    MUTE = "mute"

    HOLD = "hold"

    SPEAKER = "speaker"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
