"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class TaskQueueRealTimeStatistics(object):
    """Implementation of the 'TaskQueueRealTimeStatistics' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            TaskQueue resource.
        activity_statistics (List[Any]): The number of current Workers by Activity.
        longest_task_waiting_age (int): The age of the longest waiting Task.
        longest_task_waiting_sid (str): The SID of the longest waiting Task.
        longest_relative_task_age_in_queue (int): The relative age in the TaskQueue
            for the longest waiting Task. Calculation is based on the time when the
            Task entered the TaskQueue.
        longest_relative_task_sid_in_queue (str): The Task SID of the Task waiting in
            the TaskQueue the longest. Calculation is based on the time when the Task
            entered the TaskQueue.
        task_queue_sid (str): The SID of the TaskQueue from which these statistics
            were calculated.
        tasks_by_priority (Any): The number of Tasks by priority. For example: `{"0":
            "10", "99": "5"}` shows 10 Tasks at priority 0 and 5 at priority 99.
        tasks_by_status (Any): The number of Tasks by their current status. For
            example: `{"pending": "1", "reserved": "3", "assigned": "2", "completed":
            "5"}`.
        total_available_workers (int): The total number of Workers in the TaskQueue
            with an `available` status. Workers with an `available` status may
            already have active interactions or may have none.
        total_eligible_workers (int): The total number of Workers eligible for Tasks
            in the TaskQueue, independent of their Activity state.
        total_tasks (int): The total number of Tasks.
        workspace_sid (str): The SID of the Workspace that contains the TaskQueue.
        url (str): The absolute URL of the TaskQueue statistics resource.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "activity_statistics": "activity_statistics",
        "longest_task_waiting_age": "longest_task_waiting_age",
        "longest_task_waiting_sid": "longest_task_waiting_sid",
        "longest_relative_task_age_in_queue": "longest_relative_task_age_in_queue",
        "longest_relative_task_sid_in_queue": "longest_relative_task_sid_in_queue",
        "task_queue_sid": "task_queue_sid",
        "tasks_by_priority": "tasks_by_priority",
        "tasks_by_status": "tasks_by_status",
        "total_available_workers": "total_available_workers",
        "total_eligible_workers": "total_eligible_workers",
        "total_tasks": "total_tasks",
        "workspace_sid": "workspace_sid",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "activity_statistics",
        "longest_task_waiting_age",
        "longest_task_waiting_sid",
        "longest_relative_task_age_in_queue",
        "longest_relative_task_sid_in_queue",
        "task_queue_sid",
        "tasks_by_priority",
        "tasks_by_status",
        "total_available_workers",
        "total_eligible_workers",
        "total_tasks",
        "workspace_sid",
        "url",
    ]

    _nullables = [
        "account_sid",
        "activity_statistics",
        "longest_task_waiting_sid",
        "longest_relative_task_sid_in_queue",
        "task_queue_sid",
        "tasks_by_priority",
        "tasks_by_status",
        "workspace_sid",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        activity_statistics=APIHelper.SKIP,
        longest_task_waiting_age=0,
        longest_task_waiting_sid=APIHelper.SKIP,
        longest_relative_task_age_in_queue=0,
        longest_relative_task_sid_in_queue=APIHelper.SKIP,
        task_queue_sid=APIHelper.SKIP,
        tasks_by_priority=APIHelper.SKIP,
        tasks_by_status=APIHelper.SKIP,
        total_available_workers=0,
        total_eligible_workers=0,
        total_tasks=0,
        workspace_sid=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TaskQueueRealTimeStatistics instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if activity_statistics is not APIHelper.SKIP:
            self.activity_statistics = activity_statistics
        self.longest_task_waiting_age = longest_task_waiting_age
        if longest_task_waiting_sid is not APIHelper.SKIP:
            self.longest_task_waiting_sid = longest_task_waiting_sid
        self.longest_relative_task_age_in_queue = longest_relative_task_age_in_queue
        if longest_relative_task_sid_in_queue is not APIHelper.SKIP:
            self.longest_relative_task_sid_in_queue =\
                 longest_relative_task_sid_in_queue
        if task_queue_sid is not APIHelper.SKIP:
            self.task_queue_sid = task_queue_sid
        if tasks_by_priority is not APIHelper.SKIP:
            self.tasks_by_priority = tasks_by_priority
        if tasks_by_status is not APIHelper.SKIP:
            self.tasks_by_status = tasks_by_status
        self.total_available_workers = total_available_workers
        self.total_eligible_workers = total_eligible_workers
        self.total_tasks = total_tasks
        if workspace_sid is not APIHelper.SKIP:
            self.workspace_sid = workspace_sid
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        activity_statistics =\
            dictionary.get("activity_statistics")\
            if "activity_statistics" in dictionary.keys()\
                else APIHelper.SKIP
        longest_task_waiting_age =\
            dictionary.get("longest_task_waiting_age")\
            if dictionary.get("longest_task_waiting_age")\
                else 0
        longest_task_waiting_sid =\
            dictionary.get("longest_task_waiting_sid")\
            if "longest_task_waiting_sid" in dictionary.keys()\
                else APIHelper.SKIP
        longest_relative_task_age_in_queue =\
            dictionary.get("longest_relative_task_age_in_queue")\
            if dictionary.get("longest_relative_task_age_in_queue")\
                else 0
        longest_relative_task_sid_in_queue =\
            dictionary.get("longest_relative_task_sid_in_queue")\
            if "longest_relative_task_sid_in_queue" in dictionary.keys()\
                else APIHelper.SKIP
        task_queue_sid =\
            dictionary.get("task_queue_sid")\
            if "task_queue_sid" in dictionary.keys()\
                else APIHelper.SKIP
        tasks_by_priority =\
            dictionary.get("tasks_by_priority")\
            if "tasks_by_priority" in dictionary.keys()\
                else APIHelper.SKIP
        tasks_by_status =\
            dictionary.get("tasks_by_status")\
            if "tasks_by_status" in dictionary.keys()\
                else APIHelper.SKIP
        total_available_workers =\
            dictionary.get("total_available_workers")\
            if dictionary.get("total_available_workers")\
                else 0
        total_eligible_workers =\
            dictionary.get("total_eligible_workers")\
            if dictionary.get("total_eligible_workers")\
                else 0
        total_tasks =\
            dictionary.get("total_tasks")\
            if dictionary.get("total_tasks")\
                else 0
        workspace_sid =\
            dictionary.get("workspace_sid")\
            if "workspace_sid" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   activity_statistics,
                   longest_task_waiting_age,
                   longest_task_waiting_sid,
                   longest_relative_task_age_in_queue,
                   longest_relative_task_sid_in_queue,
                   task_queue_sid,
                   tasks_by_priority,
                   tasks_by_status,
                   total_available_workers,
                   total_eligible_workers,
                   total_tasks,
                   workspace_sid,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _activity_statistics=(
            self.activity_statistics
            if hasattr(self, "activity_statistics")
            else None
        )
        _longest_task_waiting_age=(
            self.longest_task_waiting_age
            if hasattr(self, "longest_task_waiting_age")
            else None
        )
        _longest_task_waiting_sid=(
            self.longest_task_waiting_sid
            if hasattr(self, "longest_task_waiting_sid")
            else None
        )
        _longest_relative_task_age_in_queue=(
            self.longest_relative_task_age_in_queue
            if hasattr(self, "longest_relative_task_age_in_queue")
            else None
        )
        _longest_relative_task_sid_in_queue=(
            self.longest_relative_task_sid_in_queue
            if hasattr(self, "longest_relative_task_sid_in_queue")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _tasks_by_priority=(
            self.tasks_by_priority
            if hasattr(self, "tasks_by_priority")
            else None
        )
        _tasks_by_status=(
            self.tasks_by_status
            if hasattr(self, "tasks_by_status")
            else None
        )
        _total_available_workers=(
            self.total_available_workers
            if hasattr(self, "total_available_workers")
            else None
        )
        _total_eligible_workers=(
            self.total_eligible_workers
            if hasattr(self, "total_eligible_workers")
            else None
        )
        _total_tasks=(
            self.total_tasks
            if hasattr(self, "total_tasks")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"activity_statistics={_activity_statistics!r}, "
            f"longest_task_waiting_age={_longest_task_waiting_age!r}, "
            f"longest_task_waiting_sid={_longest_task_waiting_sid!r}, "
            f"longest_relative_task_age_in_queue={_longest_relative_task_age_in_queue!r}, "
            f"longest_relative_task_sid_in_queue={_longest_relative_task_sid_in_queue!r}, "
            f"task_queue_sid={_task_queue_sid!r}, "
            f"tasks_by_priority={_tasks_by_priority!r}, "
            f"tasks_by_status={_tasks_by_status!r}, "
            f"total_available_workers={_total_available_workers!r}, "
            f"total_eligible_workers={_total_eligible_workers!r}, "
            f"total_tasks={_total_tasks!r}, "
            f"workspace_sid={_workspace_sid!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _activity_statistics=(
            self.activity_statistics
            if hasattr(self, "activity_statistics")
            else None
        )
        _longest_task_waiting_age=(
            self.longest_task_waiting_age
            if hasattr(self, "longest_task_waiting_age")
            else None
        )
        _longest_task_waiting_sid=(
            self.longest_task_waiting_sid
            if hasattr(self, "longest_task_waiting_sid")
            else None
        )
        _longest_relative_task_age_in_queue=(
            self.longest_relative_task_age_in_queue
            if hasattr(self, "longest_relative_task_age_in_queue")
            else None
        )
        _longest_relative_task_sid_in_queue=(
            self.longest_relative_task_sid_in_queue
            if hasattr(self, "longest_relative_task_sid_in_queue")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _tasks_by_priority=(
            self.tasks_by_priority
            if hasattr(self, "tasks_by_priority")
            else None
        )
        _tasks_by_status=(
            self.tasks_by_status
            if hasattr(self, "tasks_by_status")
            else None
        )
        _total_available_workers=(
            self.total_available_workers
            if hasattr(self, "total_available_workers")
            else None
        )
        _total_eligible_workers=(
            self.total_eligible_workers
            if hasattr(self, "total_eligible_workers")
            else None
        )
        _total_tasks=(
            self.total_tasks
            if hasattr(self, "total_tasks")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"activity_statistics={_activity_statistics!s}, "
            f"longest_task_waiting_age={_longest_task_waiting_age!s}, "
            f"longest_task_waiting_sid={_longest_task_waiting_sid!s}, "
            f"longest_relative_task_age_in_queue={_longest_relative_task_age_in_queue!s}, "
            f"longest_relative_task_sid_in_queue={_longest_relative_task_sid_in_queue!s}, "
            f"task_queue_sid={_task_queue_sid!s}, "
            f"tasks_by_priority={_tasks_by_priority!s}, "
            f"tasks_by_status={_tasks_by_status!s}, "
            f"total_available_workers={_total_available_workers!s}, "
            f"total_eligible_workers={_total_eligible_workers!s}, "
            f"total_tasks={_total_tasks!s}, "
            f"workspace_sid={_workspace_sid!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
