"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class TaskRouterTask(object):
    """Implementation of the 'TaskRouterTask' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            Task resource.
        age (int): The number of seconds since the Task was created.
        assignment_status (TaskStatus): The current status of the Task's assignment.
            Can be: `pending`, `reserved`, `assigned`, `canceled`, `wrapping`, or
            `completed`.
        attributes (str): The JSON string with custom attributes of the work.
            **Note** If this property has been assigned a value, it will only be
            displayed in FETCH action that returns a single resource. Otherwise, it
            will be null.
        addons (str): An object that contains the
            [Add-on](https://www.twilio.com/docs/add-ons) data for all installed
            Add-ons.
        date_created (datetime): The date and time in GMT when the resource was
            created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        date_updated (datetime): The date and time in GMT when the resource was last
            updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        task_queue_entered_date (datetime): The date and time in GMT when the Task
            entered the TaskQueue, specified in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        priority (int): The current priority score of the Task as assigned to a
            Worker by the workflow. Tasks with higher priority values will be
            assigned before Tasks with lower values.
        reason (str): The reason the Task was canceled or completed, if applicable.
        sid (str): The unique string that we created to identify the Task resource.
        task_queue_sid (str): The SID of the TaskQueue.
        task_queue_friendly_name (str): The friendly name of the TaskQueue.
        task_channel_sid (str): The SID of the TaskChannel.
        task_channel_unique_name (str): The unique name of the TaskChannel.
        timeout (int): The amount of time in seconds that the Task can live before
            being assigned.
        workflow_sid (str): The SID of the Workflow that is controlling the Task.
        workflow_friendly_name (str): The friendly name of the Workflow that is
            controlling the Task.
        workspace_sid (str): The SID of the Workspace that contains the Task.
        url (str): The absolute URL of the Task resource.
        links (Any): The URLs of related resources.
        virtual_start_time (datetime): The date and time in GMT indicating the
            ordering for routing of the Task specified in [ISO
            8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        ignore_capacity (bool): A boolean that indicates if the Task should respect a
            Worker's capacity and availability during assignment. This field can only
            be used when the `RoutingTarget` field is set to a Worker SID. By setting
            `IgnoreCapacity` to a value of `true`, `1`, or `yes`, the Task will be
            routed to the Worker without respecting their capacity and availability.
            Any other value will enforce the Worker's capacity and availability. The
            default value of `IgnoreCapacity` is `true` when the `RoutingTarget` is
            set to a Worker SID.
        routing_target (str): A SID of a Worker, Queue, or Workflow to route a Task to
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "age": "age",
        "assignment_status": "assignment_status",
        "attributes": "attributes",
        "addons": "addons",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "task_queue_entered_date": "task_queue_entered_date",
        "priority": "priority",
        "reason": "reason",
        "sid": "sid",
        "task_queue_sid": "task_queue_sid",
        "task_queue_friendly_name": "task_queue_friendly_name",
        "task_channel_sid": "task_channel_sid",
        "task_channel_unique_name": "task_channel_unique_name",
        "timeout": "timeout",
        "workflow_sid": "workflow_sid",
        "workflow_friendly_name": "workflow_friendly_name",
        "workspace_sid": "workspace_sid",
        "url": "url",
        "links": "links",
        "virtual_start_time": "virtual_start_time",
        "ignore_capacity": "ignore_capacity",
        "routing_target": "routing_target",
    }

    _optionals = [
        "account_sid",
        "age",
        "assignment_status",
        "attributes",
        "addons",
        "date_created",
        "date_updated",
        "task_queue_entered_date",
        "priority",
        "reason",
        "sid",
        "task_queue_sid",
        "task_queue_friendly_name",
        "task_channel_sid",
        "task_channel_unique_name",
        "timeout",
        "workflow_sid",
        "workflow_friendly_name",
        "workspace_sid",
        "url",
        "links",
        "virtual_start_time",
        "ignore_capacity",
        "routing_target",
    ]

    _nullables = [
        "account_sid",
        "attributes",
        "addons",
        "date_created",
        "date_updated",
        "task_queue_entered_date",
        "reason",
        "sid",
        "task_queue_sid",
        "task_queue_friendly_name",
        "task_channel_sid",
        "task_channel_unique_name",
        "workflow_sid",
        "workflow_friendly_name",
        "workspace_sid",
        "url",
        "links",
        "virtual_start_time",
        "ignore_capacity",
        "routing_target",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        age=0,
        assignment_status=APIHelper.SKIP,
        attributes=APIHelper.SKIP,
        addons=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        task_queue_entered_date=APIHelper.SKIP,
        priority=0,
        reason=APIHelper.SKIP,
        sid=APIHelper.SKIP,
        task_queue_sid=APIHelper.SKIP,
        task_queue_friendly_name=APIHelper.SKIP,
        task_channel_sid=APIHelper.SKIP,
        task_channel_unique_name=APIHelper.SKIP,
        timeout=0,
        workflow_sid=APIHelper.SKIP,
        workflow_friendly_name=APIHelper.SKIP,
        workspace_sid=APIHelper.SKIP,
        url=APIHelper.SKIP,
        links=APIHelper.SKIP,
        virtual_start_time=APIHelper.SKIP,
        ignore_capacity=APIHelper.SKIP,
        routing_target=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TaskRouterTask instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        self.age = age
        if assignment_status is not APIHelper.SKIP:
            self.assignment_status = assignment_status
        if attributes is not APIHelper.SKIP:
            self.attributes = attributes
        if addons is not APIHelper.SKIP:
            self.addons = addons
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if task_queue_entered_date is not APIHelper.SKIP:
            self.task_queue_entered_date =\
                 APIHelper.apply_datetime_converter(
                task_queue_entered_date, APIHelper.RFC3339DateTime)\
                 if task_queue_entered_date else None
        self.priority = priority
        if reason is not APIHelper.SKIP:
            self.reason = reason
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if task_queue_sid is not APIHelper.SKIP:
            self.task_queue_sid = task_queue_sid
        if task_queue_friendly_name is not APIHelper.SKIP:
            self.task_queue_friendly_name = task_queue_friendly_name
        if task_channel_sid is not APIHelper.SKIP:
            self.task_channel_sid = task_channel_sid
        if task_channel_unique_name is not APIHelper.SKIP:
            self.task_channel_unique_name = task_channel_unique_name
        self.timeout = timeout
        if workflow_sid is not APIHelper.SKIP:
            self.workflow_sid = workflow_sid
        if workflow_friendly_name is not APIHelper.SKIP:
            self.workflow_friendly_name = workflow_friendly_name
        if workspace_sid is not APIHelper.SKIP:
            self.workspace_sid = workspace_sid
        if url is not APIHelper.SKIP:
            self.url = url
        if links is not APIHelper.SKIP:
            self.links = links
        if virtual_start_time is not APIHelper.SKIP:
            self.virtual_start_time =\
                 APIHelper.apply_datetime_converter(
                virtual_start_time, APIHelper.RFC3339DateTime)\
                 if virtual_start_time else None
        if ignore_capacity is not APIHelper.SKIP:
            self.ignore_capacity = ignore_capacity
        if routing_target is not APIHelper.SKIP:
            self.routing_target = routing_target

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        age =\
            dictionary.get("age")\
            if dictionary.get("age")\
                else 0
        assignment_status =\
            dictionary.get("assignment_status")\
            if dictionary.get("assignment_status")\
                else APIHelper.SKIP
        attributes =\
            dictionary.get("attributes")\
            if "attributes" in dictionary.keys()\
                else APIHelper.SKIP
        addons =\
            dictionary.get("addons")\
            if "addons" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        if "task_queue_entered_date" in dictionary.keys():
            task_queue_entered_date = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("task_queue_entered_date")).datetime\
                if dictionary.get("task_queue_entered_date") else None

        else:
            task_queue_entered_date = APIHelper.SKIP
        priority =\
            dictionary.get("priority")\
            if dictionary.get("priority")\
                else 0
        reason =\
            dictionary.get("reason")\
            if "reason" in dictionary.keys()\
                else APIHelper.SKIP
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        task_queue_sid =\
            dictionary.get("task_queue_sid")\
            if "task_queue_sid" in dictionary.keys()\
                else APIHelper.SKIP
        task_queue_friendly_name =\
            dictionary.get("task_queue_friendly_name")\
            if "task_queue_friendly_name" in dictionary.keys()\
                else APIHelper.SKIP
        task_channel_sid =\
            dictionary.get("task_channel_sid")\
            if "task_channel_sid" in dictionary.keys()\
                else APIHelper.SKIP
        task_channel_unique_name =\
            dictionary.get("task_channel_unique_name")\
            if "task_channel_unique_name" in dictionary.keys()\
                else APIHelper.SKIP
        timeout =\
            dictionary.get("timeout")\
            if dictionary.get("timeout")\
                else 0
        workflow_sid =\
            dictionary.get("workflow_sid")\
            if "workflow_sid" in dictionary.keys()\
                else APIHelper.SKIP
        workflow_friendly_name =\
            dictionary.get("workflow_friendly_name")\
            if "workflow_friendly_name" in dictionary.keys()\
                else APIHelper.SKIP
        workspace_sid =\
            dictionary.get("workspace_sid")\
            if "workspace_sid" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        links =\
            dictionary.get("links")\
            if "links" in dictionary.keys()\
                else APIHelper.SKIP
        if "virtual_start_time" in dictionary.keys():
            virtual_start_time = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("virtual_start_time")).datetime\
                if dictionary.get("virtual_start_time") else None

        else:
            virtual_start_time = APIHelper.SKIP
        ignore_capacity =\
            dictionary.get("ignore_capacity")\
            if "ignore_capacity" in dictionary.keys()\
                else APIHelper.SKIP
        routing_target =\
            dictionary.get("routing_target")\
            if "routing_target" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   age,
                   assignment_status,
                   attributes,
                   addons,
                   date_created,
                   date_updated,
                   task_queue_entered_date,
                   priority,
                   reason,
                   sid,
                   task_queue_sid,
                   task_queue_friendly_name,
                   task_channel_sid,
                   task_channel_unique_name,
                   timeout,
                   workflow_sid,
                   workflow_friendly_name,
                   workspace_sid,
                   url,
                   links,
                   virtual_start_time,
                   ignore_capacity,
                   routing_target,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _age=(
            self.age
            if hasattr(self, "age")
            else None
        )
        _assignment_status=(
            self.assignment_status
            if hasattr(self, "assignment_status")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _addons=(
            self.addons
            if hasattr(self, "addons")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _task_queue_entered_date=(
            self.task_queue_entered_date
            if hasattr(self, "task_queue_entered_date")
            else None
        )
        _priority=(
            self.priority
            if hasattr(self, "priority")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _task_queue_friendly_name=(
            self.task_queue_friendly_name
            if hasattr(self, "task_queue_friendly_name")
            else None
        )
        _task_channel_sid=(
            self.task_channel_sid
            if hasattr(self, "task_channel_sid")
            else None
        )
        _task_channel_unique_name=(
            self.task_channel_unique_name
            if hasattr(self, "task_channel_unique_name")
            else None
        )
        _timeout=(
            self.timeout
            if hasattr(self, "timeout")
            else None
        )
        _workflow_sid=(
            self.workflow_sid
            if hasattr(self, "workflow_sid")
            else None
        )
        _workflow_friendly_name=(
            self.workflow_friendly_name
            if hasattr(self, "workflow_friendly_name")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _virtual_start_time=(
            self.virtual_start_time
            if hasattr(self, "virtual_start_time")
            else None
        )
        _ignore_capacity=(
            self.ignore_capacity
            if hasattr(self, "ignore_capacity")
            else None
        )
        _routing_target=(
            self.routing_target
            if hasattr(self, "routing_target")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"age={_age!r}, "
            f"assignment_status={_assignment_status!r}, "
            f"attributes={_attributes!r}, "
            f"addons={_addons!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"task_queue_entered_date={_task_queue_entered_date!r}, "
            f"priority={_priority!r}, "
            f"reason={_reason!r}, "
            f"sid={_sid!r}, "
            f"task_queue_sid={_task_queue_sid!r}, "
            f"task_queue_friendly_name={_task_queue_friendly_name!r}, "
            f"task_channel_sid={_task_channel_sid!r}, "
            f"task_channel_unique_name={_task_channel_unique_name!r}, "
            f"timeout={_timeout!r}, "
            f"workflow_sid={_workflow_sid!r}, "
            f"workflow_friendly_name={_workflow_friendly_name!r}, "
            f"workspace_sid={_workspace_sid!r}, "
            f"url={_url!r}, "
            f"links={_links!r}, "
            f"virtual_start_time={_virtual_start_time!r}, "
            f"ignore_capacity={_ignore_capacity!r}, "
            f"routing_target={_routing_target!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _age=(
            self.age
            if hasattr(self, "age")
            else None
        )
        _assignment_status=(
            self.assignment_status
            if hasattr(self, "assignment_status")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _addons=(
            self.addons
            if hasattr(self, "addons")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _task_queue_entered_date=(
            self.task_queue_entered_date
            if hasattr(self, "task_queue_entered_date")
            else None
        )
        _priority=(
            self.priority
            if hasattr(self, "priority")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _task_queue_sid=(
            self.task_queue_sid
            if hasattr(self, "task_queue_sid")
            else None
        )
        _task_queue_friendly_name=(
            self.task_queue_friendly_name
            if hasattr(self, "task_queue_friendly_name")
            else None
        )
        _task_channel_sid=(
            self.task_channel_sid
            if hasattr(self, "task_channel_sid")
            else None
        )
        _task_channel_unique_name=(
            self.task_channel_unique_name
            if hasattr(self, "task_channel_unique_name")
            else None
        )
        _timeout=(
            self.timeout
            if hasattr(self, "timeout")
            else None
        )
        _workflow_sid=(
            self.workflow_sid
            if hasattr(self, "workflow_sid")
            else None
        )
        _workflow_friendly_name=(
            self.workflow_friendly_name
            if hasattr(self, "workflow_friendly_name")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _virtual_start_time=(
            self.virtual_start_time
            if hasattr(self, "virtual_start_time")
            else None
        )
        _ignore_capacity=(
            self.ignore_capacity
            if hasattr(self, "ignore_capacity")
            else None
        )
        _routing_target=(
            self.routing_target
            if hasattr(self, "routing_target")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"age={_age!s}, "
            f"assignment_status={_assignment_status!s}, "
            f"attributes={_attributes!s}, "
            f"addons={_addons!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"task_queue_entered_date={_task_queue_entered_date!s}, "
            f"priority={_priority!s}, "
            f"reason={_reason!s}, "
            f"sid={_sid!s}, "
            f"task_queue_sid={_task_queue_sid!s}, "
            f"task_queue_friendly_name={_task_queue_friendly_name!s}, "
            f"task_channel_sid={_task_channel_sid!s}, "
            f"task_channel_unique_name={_task_channel_unique_name!s}, "
            f"timeout={_timeout!s}, "
            f"workflow_sid={_workflow_sid!s}, "
            f"workflow_friendly_name={_workflow_friendly_name!s}, "
            f"workspace_sid={_workspace_sid!s}, "
            f"url={_url!s}, "
            f"links={_links!s}, "
            f"virtual_start_time={_virtual_start_time!s}, "
            f"ignore_capacity={_ignore_capacity!s}, "
            f"routing_target={_routing_target!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
