"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TaskQueueTaskOrder(object):
    """Implementation of the 'TaskQueueTaskOrder' enum.

    How Tasks will be assigned to Workers. Set this parameter to `LIFO` to assign
    most recently created Task first or `FIFO` to assign the oldest Task. Default is
    FIFO. [Click
    here](https://www.twilio.com/docs/taskrouter/queue-ordering-last-first-out-lifo)
    to learn more.

    Attributes:
        FIFO: The enum member of type str.
        LIFO: The enum member of type str.

    """

    FIFO = "FIFO"

    LIFO = "LIFO"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
