"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class VerificationCheckEnumChannel(object):
    """Implementation of the 'VerificationCheckEnumChannel' enum.

    The verification method to use. One of:
    [`email`](https://www.twilio.com/docs/verify/email), `sms`, `whatsapp`, `call`,
    or `sna`.

    Attributes:
        SMS: The enum member of type str.
        CALL: The enum member of type str.
        EMAIL: The enum member of type str.
        WHATSAPP: The enum member of type str.
        SNA: The enum member of type str.

    """

    SMS = "sms"

    CALL = "call"

    EMAIL = "email"

    WHATSAPP = "whatsapp"

    SNA = "sna"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
