"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class WorkersRealTimeStatistics(object):
    """Implementation of the 'WorkersRealTimeStatistics' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            Worker resource.
        activity_statistics (List[Any]): The number of current Workers by Activity.
        total_workers (int): The total number of Workers.
        workspace_sid (str): The SID of the Workspace that contains the Workers.
        url (str): The absolute URL of the Workers statistics resource.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "activity_statistics": "activity_statistics",
        "total_workers": "total_workers",
        "workspace_sid": "workspace_sid",
        "url": "url",
    }

    _optionals = [
        "account_sid",
        "activity_statistics",
        "total_workers",
        "workspace_sid",
        "url",
    ]

    _nullables = [
        "account_sid",
        "activity_statistics",
        "workspace_sid",
        "url",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        activity_statistics=APIHelper.SKIP,
        total_workers=0,
        workspace_sid=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a WorkersRealTimeStatistics instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if activity_statistics is not APIHelper.SKIP:
            self.activity_statistics = activity_statistics
        self.total_workers = total_workers
        if workspace_sid is not APIHelper.SKIP:
            self.workspace_sid = workspace_sid
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        activity_statistics =\
            dictionary.get("activity_statistics")\
            if "activity_statistics" in dictionary.keys()\
                else APIHelper.SKIP
        total_workers =\
            dictionary.get("total_workers")\
            if dictionary.get("total_workers")\
                else 0
        workspace_sid =\
            dictionary.get("workspace_sid")\
            if "workspace_sid" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   activity_statistics,
                   total_workers,
                   workspace_sid,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _activity_statistics=(
            self.activity_statistics
            if hasattr(self, "activity_statistics")
            else None
        )
        _total_workers=(
            self.total_workers
            if hasattr(self, "total_workers")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"activity_statistics={_activity_statistics!r}, "
            f"total_workers={_total_workers!r}, "
            f"workspace_sid={_workspace_sid!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _activity_statistics=(
            self.activity_statistics
            if hasattr(self, "activity_statistics")
            else None
        )
        _total_workers=(
            self.total_workers
            if hasattr(self, "total_workers")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"activity_statistics={_activity_statistics!s}, "
            f"total_workers={_total_workers!s}, "
            f"workspace_sid={_workspace_sid!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
