"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from twilioapis.api_helper import APIHelper


class WorkerReservation(object):
    """Implementation of the 'WorkerReservation' model.

    Attributes:
        account_sid (str): The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created the
            WorkerReservation resource.
        date_created (datetime): The date and time in GMT when the resource was
            created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        date_updated (datetime): The date and time in GMT when the resource was last
            updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
            format.
        reservation_status (WorkerReservationStatus): The current status of the
            reservation. Can be: `pending`, `accepted`, `rejected`, `timeout`,
            `canceled`, or `rescinded`.
        sid (str): The unique string that we created to identify the
            WorkerReservation resource.
        task_sid (str): The SID of the reserved Task resource.
        worker_name (str): The `friendly_name` of the Worker that is reserved.
        worker_sid (str): The SID of the reserved Worker resource.
        workspace_sid (str): The SID of the Workspace that this worker is contained
            within.
        url (str): The absolute URL of the WorkerReservation resource.
        links (Any): The URLs of related resources.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": "account_sid",
        "date_created": "date_created",
        "date_updated": "date_updated",
        "reservation_status": "reservation_status",
        "sid": "sid",
        "task_sid": "task_sid",
        "worker_name": "worker_name",
        "worker_sid": "worker_sid",
        "workspace_sid": "workspace_sid",
        "url": "url",
        "links": "links",
    }

    _optionals = [
        "account_sid",
        "date_created",
        "date_updated",
        "reservation_status",
        "sid",
        "task_sid",
        "worker_name",
        "worker_sid",
        "workspace_sid",
        "url",
        "links",
    ]

    _nullables = [
        "account_sid",
        "date_created",
        "date_updated",
        "sid",
        "task_sid",
        "worker_name",
        "worker_sid",
        "workspace_sid",
        "url",
        "links",
    ]

    def __init__(
        self,
        account_sid=APIHelper.SKIP,
        date_created=APIHelper.SKIP,
        date_updated=APIHelper.SKIP,
        reservation_status=APIHelper.SKIP,
        sid=APIHelper.SKIP,
        task_sid=APIHelper.SKIP,
        worker_name=APIHelper.SKIP,
        worker_sid=APIHelper.SKIP,
        workspace_sid=APIHelper.SKIP,
        url=APIHelper.SKIP,
        links=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a WorkerReservation instance."""
        # Initialize members of the class
        if account_sid is not APIHelper.SKIP:
            self.account_sid = account_sid
        if date_created is not APIHelper.SKIP:
            self.date_created =\
                 APIHelper.apply_datetime_converter(
                date_created, APIHelper.RFC3339DateTime)\
                 if date_created else None
        if date_updated is not APIHelper.SKIP:
            self.date_updated =\
                 APIHelper.apply_datetime_converter(
                date_updated, APIHelper.RFC3339DateTime)\
                 if date_updated else None
        if reservation_status is not APIHelper.SKIP:
            self.reservation_status = reservation_status
        if sid is not APIHelper.SKIP:
            self.sid = sid
        if task_sid is not APIHelper.SKIP:
            self.task_sid = task_sid
        if worker_name is not APIHelper.SKIP:
            self.worker_name = worker_name
        if worker_sid is not APIHelper.SKIP:
            self.worker_sid = worker_sid
        if workspace_sid is not APIHelper.SKIP:
            self.workspace_sid = workspace_sid
        if url is not APIHelper.SKIP:
            self.url = url
        if links is not APIHelper.SKIP:
            self.links = links

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid =\
            dictionary.get("account_sid")\
            if "account_sid" in dictionary.keys()\
                else APIHelper.SKIP
        if "date_created" in dictionary.keys():
            date_created = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_created")).datetime\
                if dictionary.get("date_created") else None

        else:
            date_created = APIHelper.SKIP
        if "date_updated" in dictionary.keys():
            date_updated = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("date_updated")).datetime\
                if dictionary.get("date_updated") else None

        else:
            date_updated = APIHelper.SKIP
        reservation_status =\
            dictionary.get("reservation_status")\
            if dictionary.get("reservation_status")\
                else APIHelper.SKIP
        sid =\
            dictionary.get("sid")\
            if "sid" in dictionary.keys()\
                else APIHelper.SKIP
        task_sid =\
            dictionary.get("task_sid")\
            if "task_sid" in dictionary.keys()\
                else APIHelper.SKIP
        worker_name =\
            dictionary.get("worker_name")\
            if "worker_name" in dictionary.keys()\
                else APIHelper.SKIP
        worker_sid =\
            dictionary.get("worker_sid")\
            if "worker_sid" in dictionary.keys()\
                else APIHelper.SKIP
        workspace_sid =\
            dictionary.get("workspace_sid")\
            if "workspace_sid" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP
        links =\
            dictionary.get("links")\
            if "links" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_sid,
                   date_created,
                   date_updated,
                   reservation_status,
                   sid,
                   task_sid,
                   worker_name,
                   worker_sid,
                   workspace_sid,
                   url,
                   links,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _reservation_status=(
            self.reservation_status
            if hasattr(self, "reservation_status")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _task_sid=(
            self.task_sid
            if hasattr(self, "task_sid")
            else None
        )
        _worker_name=(
            self.worker_name
            if hasattr(self, "worker_name")
            else None
        )
        _worker_sid=(
            self.worker_sid
            if hasattr(self, "worker_sid")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!r}, "
            f"date_created={_date_created!r}, "
            f"date_updated={_date_updated!r}, "
            f"reservation_status={_reservation_status!r}, "
            f"sid={_sid!r}, "
            f"task_sid={_task_sid!r}, "
            f"worker_name={_worker_name!r}, "
            f"worker_sid={_worker_sid!r}, "
            f"workspace_sid={_workspace_sid!r}, "
            f"url={_url!r}, "
            f"links={_links!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_sid=(
            self.account_sid
            if hasattr(self, "account_sid")
            else None
        )
        _date_created=(
            self.date_created
            if hasattr(self, "date_created")
            else None
        )
        _date_updated=(
            self.date_updated
            if hasattr(self, "date_updated")
            else None
        )
        _reservation_status=(
            self.reservation_status
            if hasattr(self, "reservation_status")
            else None
        )
        _sid=(
            self.sid
            if hasattr(self, "sid")
            else None
        )
        _task_sid=(
            self.task_sid
            if hasattr(self, "task_sid")
            else None
        )
        _worker_name=(
            self.worker_name
            if hasattr(self, "worker_name")
            else None
        )
        _worker_sid=(
            self.worker_sid
            if hasattr(self, "worker_sid")
            else None
        )
        _workspace_sid=(
            self.workspace_sid
            if hasattr(self, "workspace_sid")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_sid={_account_sid!s}, "
            f"date_created={_date_created!s}, "
            f"date_updated={_date_updated!s}, "
            f"reservation_status={_reservation_status!s}, "
            f"sid={_sid!s}, "
            f"task_sid={_task_sid!s}, "
            f"worker_name={_worker_name!s}, "
            f"worker_sid={_worker_sid!s}, "
            f"workspace_sid={_workspace_sid!s}, "
            f"url={_url!s}, "
            f"links={_links!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
