"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from twilioapis.api_helper import APIHelper
from twilioapis.apis.base_api import BaseApi
from twilioapis.configuration import Server
from twilioapis.http.http_method_enum import (
    HttpMethodEnum,
)
from twilioapis.models.notification import Notification


class NotifyV1NotificationApi(BaseApi):
    """A Controller to access Endpoints in the twilioapis API."""

    def __init__(self, config):
        """Initialize NotifyV1NotificationApi object."""
        super(NotifyV1NotificationApi, self).__init__(config)

    def create_notification(self,
                            service_sid,
                            body=None,
                            priority=None,
                            ttl=None,
                            title=None,
                            sound=None,
                            action=None,
                            data=None,
                            apn=None,
                            gcm=None,
                            sms=None,
                            facebook_messenger=None,
                            fcm=None,
                            segment=None,
                            alexa=None,
                            to_binding=None,
                            delivery_callback_url=None,
                            identity=None,
                            tag=None):
        """Perform a POST request to /v1/Services/{ServiceSid}/Notifications.

        Args:
            service_sid (str): The SID of the
                [Service](https://www.twilio.com/docs/notify/api/service-resource) to
                create the resource under.
            body (str, optional): The notification text. For FCM and GCM, translates
                to `data.twi_body`. For APNS, translates to `aps.alert.body`. For
                SMS, translates to `body`. SMS requires either this `body` value, or
                `media_urls` attribute defined in the `sms` parameter of the
                notification.
            priority (NotifPriority, optional): The priority of the notification. Can
                be: `low` or `high` and the default is `high`. A value of `low`
                optimizes the client app's battery consumption; however,
                notifications may be delivered with unspecified delay. For FCM and
                GCM, `low` priority is the same as `Normal` priority. For APNS `low`
                priority is the same as `5`. A value of `high` sends the notification
                immediately, and can wake up a sleeping device. For FCM and GCM,
                `high` is the same as `High` priority. For APNS, `high` is a priority
                `10`. SMS does not support this property.
            ttl (int, optional): How long, in seconds, the notification is valid. Can
                be an integer between 0 and 2,419,200, which is 4 weeks, the default
                and the maximum supported time to live (TTL). Delivery should be
                attempted if the device is offline until the TTL elapses. Zero means
                that the notification delivery is attempted immediately, only once,
                and is not stored for future delivery. SMS does not support this
                property.
            title (str, optional): The notification title. For FCM and GCM, this
                translates to the `data.twi_title` value. For APNS, this translates
                to the `aps.alert.title` value. SMS does not support this property.
                This field is not visible on iOS phones and tablets but appears on
                Apple Watch and Android devices.
            sound (str, optional): The name of the sound to be played for the
                notification. For FCM and GCM, this Translates to `data.twi_sound`.
                For APNS, this translates to `aps.sound`.  SMS does not support this
                property.
            action (str, optional): The actions to display for the notification. For
                APNS, translates to the `aps.category` value. For GCM, translates to
                the `data.twi_action` value. For SMS, this parameter is not supported
                and is omitted from deliveries to those channels.
            data (Any, optional): The custom key-value pairs of the notification's
                payload. For FCM and GCM, this value translates to `data` in the FCM
                and GCM payloads. FCM and GCM [reserve certain
                keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref
                ) that cannot be used in those channels. For APNS, attributes of
                `data` are inserted into the APNS payload as custom properties
                outside of the `aps` dictionary. In all channels, we reserve keys
                that start with `twi_` for future use. Custom keys that start with
                `twi_` are not allowed and are rejected as 400 Bad request with no
                delivery attempted. For SMS, this parameter is not supported and is
                omitted from deliveries to those channels.
            apn (Any, optional): The APNS-specific payload that overrides
                corresponding attributes in the generic payload for APNS Bindings.
                This property maps to the APNS `Payload` item, therefore the `aps`
                key must be used to change standard attributes. Adds custom key-value
                pairs to the root of the dictionary. See the [APNS
                documentation](https://developer.apple.com/library/content/documentati
                on/NetworkingInternet/Conceptual/RemoteNotificationsPG/Communicatingwi
                thAPNs.html) for more details. We reserve keys that start with `twi_`
                for future use. Custom keys that start with `twi_` are not allowed.
            gcm (Any, optional): The GCM-specific payload that overrides
                corresponding attributes in the generic payload for GCM Bindings.
                This property maps to the root JSON dictionary. See the [GCM
                documentation](https://firebase.google.com/docs/cloud-messaging/http-s
                erver-ref) for more details. Target parameters `to`,
                `registration_ids`, and `notification_key` are not allowed. We
                reserve keys that start with `twi_` for future use. Custom keys that
                start with `twi_` are not allowed. GCM also [reserves certain
                keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref
                ).
            sms (Any, optional): The SMS-specific payload that overrides
                corresponding attributes in the generic payload for SMS Bindings.
                Each attribute in this value maps to the corresponding `form`
                parameter of the Twilio
                [Message](https://www.twilio.com/docs/sms/quickstart) resource.
                These parameters of the Message resource are supported in snake case
                format: `body`, `media_urls`, `status_callback`, and `max_price`.
                The `status_callback` parameter overrides the corresponding parameter
                in the messaging service, if configured. The `media_urls` property
                expects a JSON array.
            facebook_messenger (Any, optional): Deprecated.
            fcm (Any, optional): The FCM-specific payload that overrides
                corresponding attributes in the generic payload for FCM Bindings.
                This property maps to the root JSON dictionary. See the [FCM
                documentation](https://firebase.google.com/docs/cloud-messaging/http-s
                erver-ref#downstream) for more details. Target parameters `to`,
                `registration_ids`, `condition`, and `notification_key` are not
                allowed in this parameter. We reserve keys that start with `twi_` for
                future use. Custom keys that start with `twi_` are not allowed. FCM
                also [reserves certain
                keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref
                ), which cannot be used in that channel.
            segment (List[str], optional): The Segment resource is deprecated. Use
                the `tag` parameter, instead.
            alexa (Any, optional): Deprecated.
            to_binding (List[str], optional): The destination address specified as a
                JSON string.  Multiple `to_binding` parameters can be included but
                the total size of the request entity should not exceed 1MB. This is
                typically sufficient for 10,000 phone numbers.
            delivery_callback_url (str, optional): URL to send webhooks.
            identity (List[str], optional): The `identity` value that uniquely
                identifies the new resource's
                [User](https://www.twilio.com/docs/chat/rest/user-resource) within
                the
                [Service](https://www.twilio.com/docs/notify/api/service-resource).
                Delivery will be attempted only to Bindings with an Identity in this
                list. No more than 20 items are allowed in this list.
            tag (List[str], optional): A tag that selects the Bindings to notify.
                Repeat this parameter to specify more than one tag, up to a total of
                5 tags. The implicit tag `all` is available to notify all Bindings in
                a Service instance. Similarly, the implicit tags `apn`, `fcm`, `gcm`,
                `sms` and `facebook-messenger` are available to notify all Bindings
                in a specific channel.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Created

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT3)
            .path("/v1/Services/{ServiceSid}/Notifications")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("ServiceSid")
                .value(service_sid)
                .is_required(True)
                .should_encode(True))
            .form_param(Parameter()
                .key("Body")
                .value(body))
            .form_param(Parameter()
                .key("Priority")
                .value(priority))
            .form_param(Parameter()
                .key("Ttl")
                .value(ttl))
            .form_param(Parameter()
                .key("Title")
                .value(title))
            .form_param(Parameter()
                .key("Sound")
                .value(sound))
            .form_param(Parameter()
                .key("Action")
                .value(action))
            .form_param(Parameter()
                .key("Data")
                .value(data))
            .form_param(Parameter()
                .key("Apn")
                .value(apn))
            .form_param(Parameter()
                .key("Gcm")
                .value(gcm))
            .form_param(Parameter()
                .key("Sms")
                .value(sms))
            .form_param(Parameter()
                .key("FacebookMessenger")
                .value(facebook_messenger))
            .form_param(Parameter()
                .key("Fcm")
                .value(fcm))
            .form_param(Parameter()
                .key("Segment")
                .value(segment))
            .form_param(Parameter()
                .key("Alexa")
                .value(alexa))
            .form_param(Parameter()
                .key("ToBinding")
                .value(to_binding))
            .form_param(Parameter()
                .key("DeliveryCallbackUrl")
                .value(delivery_callback_url))
            .form_param(Parameter()
                .key("Identity")
                .value(identity))
            .form_param(Parameter()
                .key("Tag")
                .value(tag))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("accountSid_authToken")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Notification.from_dictionary)
            .is_api_response(True),
        ).execute()
