"""twilioapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from twilioapis.api_helper import APIHelper
from twilioapis.apis.base_api import BaseApi
from twilioapis.configuration import Server
from twilioapis.http.http_method_enum import (
    HttpMethodEnum,
)
from twilioapis.models.api_v_2010_account_message import (
    ApiV2010AccountMessage,
)


class SmsApi(BaseApi):
    """A Controller to access Endpoints in the twilioapis API."""

    def __init__(self, config):
        """Initialize SmsApi object."""
        super(SmsApi, self).__init__(config)

    def create_message(self,
                       account_sid,
                       to,
                       status_callback=None,
                       application_sid=None,
                       max_price=None,
                       provide_feedback=None,
                       attempt=None,
                       validity_period=None,
                       force_delivery=None,
                       content_retention=None,
                       address_retention=None,
                       smart_encoded=None,
                       persistent_action=None,
                       traffic_type=None,
                       shorten_urls=None,
                       schedule_type=None,
                       send_at=None,
                       send_as_mms=None,
                       content_variables=None,
                       risk_check=None,
                       mfrom=None,
                       messaging_service_sid=None,
                       body=None,
                       media_url=None,
                       content_sid=None):
        """Perform a POST request to
        /2010-04-01/Accounts/{AccountSid}/Messages.json.

        Send a message

        Args:
            account_sid (str): The SID of the
                [Account](https://www.twilio.com/docs/iam/api/account) creating the
                Message resource.
            to (str): The recipient's phone number in
                [E.164](https://www.twilio.com/docs/glossary/what-e164) format (for
                SMS/MMS) or [channel
                address](https://www.twilio.com/docs/messaging/channels), e.g.
                `whatsapp:+15552229999`.
            status_callback (str, optional): The URL of the endpoint to which Twilio
                sends [Message status callback
                requests](https://www.twilio.com/docs/sms/api/message-resource#twilios
                -request-to-the-statuscallback-url). URL must contain a valid
                hostname and underscores are not allowed. If you include this
                parameter with the `messaging_service_sid`, Twilio uses this URL
                instead of the Status Callback URL of the [Messaging
                Service](https://www.twilio.com/docs/messaging/api/service-resource).
            application_sid (str, optional): The SID of the associated [TwiML
                Application](https://www.twilio.com/docs/usage/api/applications).
                [Message status callback
                requests](https://www.twilio.com/docs/sms/api/message-resource#twilios
                -request-to-the-statuscallback-url) are sent to the TwiML App's
                `message_status_callback` URL. Note that the `status_callback`
                parameter of a request takes priority over the `application_sid`
                parameter; if both are included `application_sid` is ignored.
            max_price (float, optional): [OBSOLETE] This parameter will no longer
                have any effect as of 2024-06-03.
            provide_feedback (bool, optional): Boolean indicating whether or not you
                intend to provide delivery confirmation feedback to Twilio (used in
                conjunction with the [Message Feedback
                subresource](https://www.twilio.com/docs/sms/api/message-feedback-reso
                urce)). Default value is `false`.
            attempt (int, optional): Total number of attempts made (including this
                request) to send the message regardless of the provider used
            validity_period (int, optional): The maximum length in seconds that the
                Message can remain in Twilio's outgoing message queue. If a queued
                Message exceeds the `validity_period`, the Message is not sent.
                Accepted values are integers from `1` to `36000`. Default value is
                `36000`. A `validity_period` greater than `5` is recommended. [Learn
                more about the validity
                period](https://www.twilio.com/blog/take-more-control-of-outbound-mess
                ages-using-validity-period-html)
            force_delivery (bool, optional): Reserved
            content_retention (MessageEnumContentRetention, optional): Determines if
                the message content can be stored or redacted based on privacy
                settings
            address_retention (MessageEnumAddressRetention, optional): Determines if
                the address can be stored or obfuscated based on privacy settings
            smart_encoded (bool, optional): Whether to detect Unicode characters that
                have a similar GSM-7 character and replace them. Can be: `true` or
                `false`.
            persistent_action (List[str], optional): Rich actions for non-SMS/MMS
                channels. Used for [sending location in WhatsApp
                messages](https://www.twilio.com/docs/whatsapp/message-features#locati
                on-messages-with-whatsapp).
            traffic_type (MessageEnumTrafficType, optional): The request form
                parameter.
            shorten_urls (bool, optional): For Messaging Services with [Link
                Shortening
                configured](https://www.twilio.com/docs/messaging/features/link-shorte
                ning) only: A Boolean indicating whether or not Twilio should shorten
                links in the `body` of the Message. Default value is `false`. If
                `true`, the `messaging_service_sid` parameter must also be provided.
            schedule_type (MessageEnumScheduleType, optional): For Messaging Services
                only: Include this parameter with a value of `fixed` in conjuction
                with the `send_time` parameter in order to [schedule a
                Message](https://www.twilio.com/docs/messaging/features/message-schedu
                ling).
            send_at (datetime, optional): The time that Twilio will send the message.
                Must be in ISO 8601 format.
            send_as_mms (bool, optional): If set to `true`, Twilio delivers the
                message as a single MMS message, regardless of the presence of media.
            content_variables (str, optional): For [Content
                Editor/API](https://www.twilio.com/docs/content) only: Key-value
                pairs of [Template
                variables](https://www.twilio.com/docs/content/using-variables-with-co
                ntent-api) and their substitution values. `content_sid` parameter
                must also be provided. If values are not defined in the
                `content_variables` parameter, the [Template's default placeholder
                values](https://www.twilio.com/docs/content/content-api-resources#crea
                te-templates) are used.
            risk_check (VerificationEnumRiskCheck, optional): Include this parameter
                with a value of `disable` to skip any kind of risk check on the
                respective message request.
            mfrom (str, optional): The sender's Twilio phone number (in
                [E.164](https://en.wikipedia.org/wiki/E.164) format), [alphanumeric
                sender ID](https://www.twilio.com/docs/sms/quickstart), [Wireless
                SIM](https://www.twilio.com/docs/iot/wireless/programmable-wireless-se
                nd-machine-machine-sms-commands), [short
                code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes)
                , or [channel
                address](https://www.twilio.com/docs/messaging/channels) (e.g.,
                `whatsapp:+15554449999`). The value of the `from` parameter must be a
                sender that is hosted within Twilio and belongs to the Account
                creating the Message. If you are using `messaging_service_sid`, this
                parameter can be empty (Twilio assigns a `from` value from the
                Messaging Service's Sender Pool) or you can provide a specific sender
                from your Sender Pool.
            messaging_service_sid (str, optional): The SID of the [Messaging
                Service](https://www.twilio.com/docs/messaging/services) you want to
                associate with the Message. When this parameter is provided and the
                `from` parameter is omitted, Twilio selects the optimal sender from
                the Messaging Service's Sender Pool. You may also provide a `from`
                parameter if you want to use a specific Sender from the Sender Pool.
            body (str, optional): The text content of the outgoing message. Can be up
                to 1,600 characters in length. SMS only: If the `body` contains more
                than 160
                [GSM-7](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-e
                ncoding) characters (or 70
                [UCS-2](https://www.twilio.com/docs/glossary/what-is-ucs-2-character-e
                ncoding) characters), the message is segmented and charged
                accordingly. For long `body` text, consider using the [send_as_mms
                parameter](https://www.twilio.com/blog/mms-for-long-text-messages).
            media_url (List[str], optional): The URL of media to include in the
                Message content. `jpeg`, `jpg`, `gif`, and `png` file types are fully
                supported by Twilio and content is formatted for delivery on
                destination devices. The media size limit is 5 MB for supported file
                types (`jpeg`, `jpg`, `png`, `gif`) and 500 KB for [other
                types](https://www.twilio.com/docs/messaging/guides/accepted-mime-type
                s) of accepted media. To send more than one image in the message,
                provide multiple `media_url` parameters in the POST request. You can
                include up to ten `media_url` parameters per message.
                [International](https://support.twilio.com/hc/en-us/articles/223179808
                -Sending-and-receiving-MMS-messages) and
                [carrier](https://support.twilio.com/hc/en-us/articles/223133707-Is-MM
                S-supported-for-all-carriers-in-US-and-Canada-) limits apply.
            content_sid (str, optional): For [Content
                Editor/API](https://www.twilio.com/docs/content) only: The SID of the
                Content Template to be used with the Message, e.g.,
                `HXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`. If this parameter is not provided,
                a Content Template is not used. Find the SID in the Console on the
                Content Editor page. For Content API users, the SID is found in
                Twilio's response when [creating the
                Template](https://www.twilio.com/docs/content/content-api-resources#cr
                eate-templates) or by [fetching your
                Templates](https://www.twilio.com/docs/content/content-api-resources#f
                etch-all-content-resources).

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Created

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT6)
            .path("/2010-04-01/Accounts/{AccountSid}/Messages.json")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("AccountSid")
                .value(account_sid)
                .is_required(True)
                .should_encode(True))
            .form_param(Parameter()
                .key("To")
                .value(to)
                .is_required(True))
            .form_param(Parameter()
                .key("StatusCallback")
                .value(status_callback))
            .form_param(Parameter()
                .key("ApplicationSid")
                .value(application_sid))
            .form_param(Parameter()
                .key("MaxPrice")
                .value(max_price))
            .form_param(Parameter()
                .key("ProvideFeedback")
                .value(provide_feedback))
            .form_param(Parameter()
                .key("Attempt")
                .value(attempt))
            .form_param(Parameter()
                .key("ValidityPeriod")
                .value(validity_period))
            .form_param(Parameter()
                .key("ForceDelivery")
                .value(force_delivery))
            .form_param(Parameter()
                .key("ContentRetention")
                .value(content_retention))
            .form_param(Parameter()
                .key("AddressRetention")
                .value(address_retention))
            .form_param(Parameter()
                .key("SmartEncoded")
                .value(smart_encoded))
            .form_param(Parameter()
                .key("PersistentAction")
                .value(persistent_action))
            .form_param(Parameter()
                .key("TrafficType")
                .value(traffic_type))
            .form_param(Parameter()
                .key("ShortenUrls")
                .value(shorten_urls))
            .form_param(Parameter()
                .key("ScheduleType")
                .value(schedule_type))
            .form_param(Parameter()
                .key("SendAt")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    send_at)))
            .form_param(Parameter()
                .key("SendAsMms")
                .value(send_as_mms))
            .form_param(Parameter()
                .key("ContentVariables")
                .value(content_variables))
            .form_param(Parameter()
                .key("RiskCheck")
                .value(risk_check))
            .form_param(Parameter()
                .key("From")
                .value(mfrom))
            .form_param(Parameter()
                .key("MessagingServiceSid")
                .value(messaging_service_sid))
            .form_param(Parameter()
                .key("Body")
                .value(body))
            .form_param(Parameter()
                .key("MediaUrl")
                .value(media_url))
            .form_param(Parameter()
                .key("ContentSid")
                .value(content_sid))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("accountSid_authToken")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ApiV2010AccountMessage.from_dictionary)
            .is_api_response(True),
        ).execute()
